"""Karar kitabı soru bankası, bölüm 4-5: kimlik ve Keycloak, veri ve sözleşme."""
from ortak import S, O

SORULAR = [
    # ------------------------------------------------------------------ KİMLİK VE KEYCLOAK
    S("K01", "kimlik", "P1", "sen",
      "Müşteriler nasıl ayrılsın (tenant modeli)?",
      "Belgedeki en etkili açık karar. Karar kaydı \"müşteri başına ayrı site\" seçti, kimlik rehberi kararı yeniden açtı. Şirket seçici, white-label seviye 2, çok şirketli kullanıcılar ve yükseltme yükü buna bağlı.",
      [
          O("tek", "Tek Frappe sitesi, müşteriler organizasyon kaydıyla ayrılır",
            "Tüm müşteriler aynı sistemde; her istek kullanıcının o şirketteki üyeliğiyle süzülür.",
            "Kurumsal mesajlaşma uygulaması: tek sistem, her şirketin kendi çalışma alanı.",
            "Artısı: bir güncelleme herkese gelir; birden çok şirkete bakan danışman (ör. mali müşavir) tek girişle çalışır. Eksisi: izolasyon hatası tüm müşterileri etkiler, bu yüzden çapraz erişim testleri her yayında zorunludur."),
          O("site", "Her müşteriye ayrı Frappe sitesi",
            "Her müşterinin ayrı veritabanı ve adresi olur.",
            "Her aileye ayrı daire: duvarlar kalın, ama her dairenin tesisatı ayrı bakım ister.",
            "Artısı: veritabanı düzeyinde ayrılık, müşteri alan adı kolay. Eksisi: her güncelleme N kez yapılır; birden çok şirkete bakan kullanıcı için ortak dizin ve ayrı bir BFF servisi gerekir."),
          O("hibrit", "Varsayılan tek site; büyük veya regüle müşteri ayrı site",
            "Çoğu müşteri paylaşımlı sistemde, özel ihtiyacı olan ayrı sitede.",
            "Bulut sağlayıcıların paylaşımlı ve ayrılmış (dedicated) paketleri.",
            "İki modelin de test edilmesi gerekir; esnek ama iş yükü en fazla."),
      ],
      oneri=["tek"],
      oneri_neden="Küçük ekip için işletim yükü en düşük model. Sözleşme iki modele dayanıklı yazıldığı için ileride büyük müşteriye ayrı site açmak yine mümkün.",
      kaynak=["Keycloak raporu (tenant kararı)", "Açık kararlar: kiracı modeli", "Uygulanabilirlik incelemesi 7"], etkiler=["B9", "M10", "M13", "G6"]),

    S("K02", "kimlik", "P1", "sen",
      "Oturum süreleri ne olsun?",
      "M25 iki sınır tanımlıyor: etkinlikle uzayan boşta kalma süresi ve yalnız yeniden girişle yenilenen mutlak bitiş. Çıkış bildirimi kaybolursa oturum en geç mutlak bitişte kapanır. Rakamlar yazılmadan canlıya çıkılamaz.",
      [
          O("rol", "Rol bazlı: yönetici ve KYC inceleyici 30 dk / 8 saat; operasyon 2 saat / 12 saat; portal 1 saat / 24 saat",
            "Yetkisi yüksek rolde süre kısa, gün boyu çalışan rolde uzun.",
            "Bankaların yönetici ekranlarını birkaç dakikada kilitlemesi, müşteri uygulamasında daha uzun tutması.",
            "Güvenlik ile rahatlık dengelenir; M25 ve Açık kararlar satırı kapanır."),
          O("siki", "Herkes için 30 dk boşta kalma / 8 saat mutlak",
            "Tek ve sıkı kural.",
            "Kamu kurumlarının e-hizmet oturumları.",
            "Gün boyu çalışan operasyon ekibi sık sık yeniden giriş yapar."),
          O("rahat", "Herkes için 8 saat boşta kalma / 7 gün mutlak",
            "Kullanıcı nadiren yeniden giriş yapar.",
            "Sosyal medya uygulamalarının haftalarca açık kalması.",
            "Önerilmez; kaçan çıkış bildiriminde oturum bir hafta açık kalabilir."),
      ],
      oneri=["rol"],
      oneri_neden="Mutlak bitişin kısa olması, kaybolan çıkış bildiriminin etkisini sınırlar. Rol bazlı süre operasyon ekibini de yormaz.",
      kaynak=["Keycloak raporu R2", "Doğrulama eki V24-2"], etkiler=["M25", "M18", "M6", "AT-20"]),

    S("K03", "kimlik", "P1", "teknik",
      "Yetkisi iptal edilen kullanıcının açık bağlantısı nasıl kesilsin?",
      "Frappe canlı güncelleme aboneliğini yalnız katılım anında kontrol ediyor. Oturum silinse bile açık bağlantı kendiliğinden kapanmıyor. M19 bunu sunucu tarafında çözmeyi şart koşuyor, ama yöntemi açık bırakıyor.",
      [
          O("periyodik", "Soket servisi oturumu periyodik olarak yeniden doğrular",
            "Her bağlantının oturumu belirli aralıkla kontrol edilir; geçersizse bağlantı kesilir.",
            "Otel kartının her kapıda yeniden okunması: iptal edilen kart kısa sürede hiçbir kapıyı açmaz.",
            "Frappe soket servisine küçük bir ek handler yazılır."),
          O("relay", "Olayları süzen ara servis (relay)",
            "Tarayıcı Frappe'ye değil, olayları yetkiye göre süzen ince bir servise bağlanır.",
            "Posta odasının her mektubu alıcının hâlâ orada çalışıp çalışmadığına bakarak dağıtması.",
            "Ayrı bir servis ve işletim yükü eklenir."),
          O("kisa", "Kısa ömürlü bağlantı ve her yeniden bağlanmada yetki kontrolü",
            "Bağlantı birkaç dakikada bir kendiliğinden yenilenir, yenilenirken yetki kontrol edilir.",
            "Otopark biletinin belirli sürede geçersizleşmesi.",
            "En basit yol; gecikme bağlantı ömrü kadardır."),
      ],
      oneri=["periyodik"],
      oneri_neden="Ek servis gerektirmez; gecikme tek bir ayarla sınırlanır.",
      kaynak=["Keycloak raporu R3", "Açık kararlar: realtime iptal"], etkiler=["M19", "B10", "AT-15", "AT-21", "AT-26"]),

    S("K04", "kimlik", "P1", "sen",
      "İptalden sonra açık bağlantıya en fazla ne kadar süre bilgi gidebilir?",
      "M19 \"azami yürürlük gecikmesi tanımlıdır\" diyor ama değer yok. Değer olmadan AT-15, AT-21 ve AT-26'nın geçip geçmediğine karar verilemez.",
      [
          O("30", "30 saniye", "Çok hızlı kesilir.", "Kapı kartının iptalden hemen sonra çalışmaması.", "Soket servisinde sık kontrol; biraz daha fazla sunucu yükü."),
          O("60", "60 saniye", "Dengeli.", "Banka kartı iptalinin bir dakika içinde yürürlüğe girmesi.", "Kontrol yükü düşük, risk penceresi kısa."),
          O("300", "5 dakika", "Gevşek.", "Çalışanın işten çıkarıldıktan sonra kartının beş dakika daha çalışması.", "Olaylar zaten yalnız \"değişti\" sinyali taşıdığı için kabul edilebilir, ama daha uzun risk penceresi."),
      ],
      oneri=["60"],
      oneri_neden="Olaylar veri taşımadığı için sızabilecek bilgi zaten sınırlı; 60 saniye güvenlik ile yük arasında makul denge.",
      kaynak=["Keycloak raporu R3", "Uygulanabilirlik incelemesi 12"], etkiler=["M19", "AT-15", "AT-21", "AT-26"]),

    S("K05", "kimlik", "P1", "sen",
      "İlk sürümde hangi giriş yöntemleri olsun?",
      "Keycloak'ın kendi özellikleri hazır; Apple, SMS, WhatsApp, Telegram ve e-posta kodu üçüncü taraf eklentiyle gelir ve her biri kabul testi ister.",
      [
          O("parola", "Parola ve e-posta doğrulaması", "Klasik giriş.", "Neredeyse her web sitesi.", "Keycloak'ın kendi özelliği; eklenti yok."),
          O("google", "Google ile giriş", "Tek tıkla giriş.", "Birçok SaaS ürünündeki \"Google ile devam et\" düğmesi.", "Keycloak'ın kendi özelliği; Google marka kuralları uygulanır."),
          O("passkey", "Passkey (parolasız, parmak izi veya yüz)", "Telefon veya bilgisayarın kilidiyle giriş.", "Büyük platformların parmak iziyle giriş seçeneği.", "Keycloak'ın kendi özelliği; yönetici ve KYC inceleyici için zorunlu."),
          O("apple", "Apple ile giriş", "iPhone kullanıcıları için tek tık.", "iOS uygulamalarındaki \"Apple ile giriş\" düğmesi.", "Eklenti ve gizli e-posta kuralları; kabul testi gerekir."),
          O("sms", "SMS kodu", "Telefona gelen 6 haneli kod.", "Bankaların tek kullanımlık şifresi.", "OTP gateway ve SMS maliyeti; toplu sahte istek (SMS pumping) koruması gerekir."),
          O("mesaj", "WhatsApp veya Telegram kodu", "Mesajlaşma uygulamasına gelen kod.", "Kimi uygulamaların kodu WhatsApp'tan göndermesi.", "Şablon onayı ve yedek kanal gerekir."),
          O("eposta", "E-posta ile gelen kod", "E-postaya gelen 6 haneli kod.", "Parolasız giriş sunan uygulamalar.", "Eklenti; kabul testi gerekir."),
      ],
      tip="cok", oneri=["parola", "google", "passkey"],
      oneri_neden="Üçü de Keycloak'ın kendi özelliği; eklenti riski yok. Diğerleri kabul testiyle sonradan eklenir.",
      kaynak=["Keycloak raporu (giriş yöntemleri)", "Kimlik rehberi"], etkiler=["M8", "AT-19"]),

    S("K06", "kimlik", "P2", "sen",
      "E-postaya giriş bağlantısı (magic link) olsun mu?",
      "Lisansı temiz ve olgun bir eklenti yok; bilinen eklenti Elastic License, yani yasak lisans.",
      [
          O("ertele", "Ertele; açık gereksinim olarak kalsın", "İlk sürümde yok.", "Önce kapıyı sağlam yap, sonra anahtarsız girişi düşün.", "M8'de açık gereksinim olarak görünür kalır."),
          O("ozgun", "Kendimiz yazalım (güvenlik incelemeli)", "Keycloak'ın kendi altyapısıyla özgün eklenti.", "Kendi kilidini yapmak: mümkün ama uzman ister.", "Tehdit modeli ve bağımsız güvenlik testi zorunlu."),
          O("ticari", "Ticari lisansla hazır eklenti", "Eklenti sahibiyle yazılı lisans.", "Kilit sistemini lisanslı firmadan almak.", "Maliyet ve sözleşme gerekir."),
      ],
      oneri=["ertele"], oneri_neden="Passkey benzer rahatlığı daha güvenli verir; magic link sonra değerlendirilebilir.",
      kaynak=["Kimlik rehberi açık kararı"], etkiler=["M8"]),

    S("K07", "kimlik", "P2", "sen",
      "Telefon numarası kimliğin neresinde olsun?",
      "Frappe kullanıcı modeli e-posta istiyor; telefonla kayıt tasarım kararı bekliyor.",
      [
          O("ikinci", "E-posta birincil kimlik, telefon ikinci kanal", "Giriş e-postayla, kod SMS'le gelebilir.", "Bankaların kullanıcı adı ile girişte SMS kodu göndermesi.", "Mevcut modelle uyumlu; ek geliştirme yok."),
          O("kullanici", "Telefon numarası kullanıcı adı olur", "Telefonla kayıt olan kişinin kullanıcı adı numarasıdır.", "Mesajlaşma uygulamalarının numarayla kayıt alması.", "Frappe e-posta ister; eşleme ve numara devri kuralları gerekir."),
          O("ozgun", "Telefonla kullanıcı arayan özgün yöntem", "Keycloak'a özel geliştirme.", "Özel yapım kilit.", "Güvenlik incelemesi zorunlu."),
      ],
      oneri=["ikinci"], oneri_neden="Numara devri ve SIM değiştirme riskleri telefonu birincil kimlik yapmayı zorlaştırır.",
      kaynak=["Kimlik rehberi açık kararı"], etkiler=["M8", "M15"]),

    S("K08", "kimlik", "P2", "sen",
      "E-postası olmayan kullanıcı hesap açabilsin mi?",
      "Frappe'de kullanıcı kaydının adı e-posta adresidir.",
      [
          O("zorunlu", "Hayır; e-posta zorunlu", "Her hesap bir e-postaya bağlıdır.", "Çoğu iş uygulamasının kayıt formu.", "Mevcut model korunur."),
          O("model", "Evet; e-postasız hesap için ayrı model", "Telefon veya kullanıcı adıyla hesap.", "Saha çalışanlarına e-postasız hesap veren sistemler.", "Frappe kullanıcı modeli ve kurtarma akışı yeniden tasarlanır."),
      ],
      oneri=["zorunlu"], oneri_neden="Hesap kurtarma, bildirim ve Frappe uyumu için en basit ve güvenli yol.",
      kaynak=["Kimlik rehberi açık kararı"], etkiler=["M11"]),

    S("K09", "kimlik", "P2", "sen",
      "Yoğun anda giriş en fazla ne kadar sürsün?",
      "Kimlik rehberi yük testi istiyor ama hedef değer açık. Hedef, giriş sayfasının bütçesini ve yük testinin eşiğini belirler.",
      [
          O("2", "Yüzde 95'inde 2 saniye", "Çok hızlı.", "Arama motorlarının anında açılması.", "Daha güçlü sunucu ve önbellek gerekir."),
          O("3", "Yüzde 95'inde 3 saniye", "Dengeli.", "İyi bir e-ticaret sitesinin ödeme sayfası.", "Makul altyapıyla ulaşılabilir."),
          O("5", "Yüzde 95'inde 5 saniye", "Gevşek.", "Yoğun saatte kamu portalı.", "Kullanıcı bekler ama iş görür."),
          O("olc", "Önce ölç, sonra karar", "Pilotta ölçülür.", "Yeni yolun trafiğini görüp ışık süresini ayarlamak.", "Hedef sayısal parametreler tablosunda açık kalır."),
      ],
      oneri=["3"], oneri_neden="Kullanıcı deneyimi ile altyapı maliyeti arasında makul hedef.",
      kaynak=["Kimlik rehberi açık kararı"], etkiler=["M7", "K3"]),

    S("K10", "kimlik", "P1", "sen",
      "Kimlik kodunu kim güvenlik açısından inceleyecek?",
      "K12 kimlik çekirdeğine dokunan her değişikliğin kodu yazmayan bir ajan ve teknik bir kişi tarafından incelenmesini istiyor. Teknik kişi henüz belli değil.",
      [
          O("ikisi", "Günlük değişiklikleri ekipten biri, faz kapılarında dış güvenlik danışmanı",
            "Rutin inceleme içeride, büyük kapılarda bağımsız uzman.",
            "Muhasebeyi şirket içinde tutup yıl sonunda bağımsız denetçiye göstermek.",
            "Kapı takvimi ve danışman bütçesi plana girer."),
          O("dis", "Yalnız dış güvenlik danışmanı",
            "Tüm kimlik değişiklikleri dış uzmana gider.",
            "Her elektrik işini lisanslı elektrikçiye yaptırmak.",
            "Ekipte geliştirici yoksa doğru seçim; maliyet ve bekleme süresi artar."),
          O("ic", "Yalnız ekipten bir geliştirici",
            "Bağımsız göz yok.",
            "Kendi yazdığın yazının imlasını kendin kontrol etmek.",
            "Kimlik çekirdeği için yetersiz."),
          O("yz", "Yalnız YZ ajanları",
            "İnceleme de YZ ile yapılır.",
            "Kendi sınavını kendin okumak.",
            "Önerilmez; kimlik çekirdeği insan onayı ister ve belge bunu şart koşuyor."),
      ],
      oneri=["ikisi"], oneri_neden="Ekipte geliştirici yoksa \"dis\" seç. Kimlik çekirdeğinde insan onayı pazarlık konusu değil.",
      kaynak=["Keycloak raporu (süreç)", "Kimlik rehberi açık kararı"], etkiler=["K12", "M4"]),

    S("K11", "kimlik", "P2", "sen",
      "Keycloak'a alternatif kimlik sunucuları izlensin mi?",
      "Kimlik rehberi Casdoor'u güvenlik kaydı düzelene kadar aday saymıyor.",
      [
          O("keycloak", "Keycloak kalır; alternatifler izlenmez", "Odak tek sistemde.", "Çalışan arabayı değiştirmemek.", "Açık kararlar satırı kapanır."),
          O("yillik", "Yılda bir alternatifleri yeniden değerlendir", "Güvenlik kayıtları düzelen alternatif gözden geçirilir.", "Sigortayı her yıl yenilerken teklif karşılaştırmak.", "Yıllık değerlendirme işi eklenir."),
      ],
      oneri=["keycloak"], oneri_neden="Köprü kimlik sunucusundan bağımsız yazıldığı için değişim ileride yine mümkün; şimdi odak dağıtmaya gerek yok.",
      kaynak=["Kimlik rehberi açık kararı"], etkiler=["M1"]),

    S("K12", "kimlik", "P2", "sen",
      "Kimlik belgesi (KYC) YZ ile işlensin mi?",
      "M23 gerçek kişinin kimlik belgesinin varsayılan olarak hiçbir modele gitmemesini istiyor; tek istisna ADR ile onaylı bir yol.",
      [
          O("yok", "Hayır; kimlik belgesi hiçbir modele gitmez, alanlar elle girilir", "En sıkı koruma.", "Bankanın kimlik fotokopisini dış firmaya vermemesi.", "M23 olduğu gibi kalır."),
          O("yerel", "Kendi sunucumuzdaki modelle yalnız alan çıkarımı", "Veri dışarı çıkmaz.", "Hastanenin kendi sunucusundaki yazılımla rapor okuması.", "GPU sunucusu ve ADR gerekir."),
          O("disi", "Sözleşmeli dış modelle", "Hukuki sözleşme ve rızayla dış model.", "Belge tarama hizmeti alan şirketler.", "KVKK aktarım dayanağı ve hukukçu onayı gerekir."),
      ],
      oneri=["yok"], oneri_neden="KYC belgesi özel risk taşır; YZ'nin getireceği zaman kazancı bu riske değmez.",
      kaynak=["Keycloak raporu R6"], etkiler=["M23", "M11"]),

    S("K13", "kimlik", "P2", "sen",
      "Misafir sepeti girişten sonra kullanıcının mevcut sepetiyle nasıl birleşsin?",
      "M21 birleştirme kuralını açık bırakıyor.",
      [
          O("sor", "Kullanıcıya sorulur", "İki sepet farklıysa kullanıcı seçer.", "Bazı e-ticaret sitelerinin \"önceki sepetin de var, birleştirelim mi?\" sorusu.", "Bir ek ekran; sürpriz yok."),
          O("topla", "Miktarlar toplanır", "İki sepet otomatik birleşir.", "Büyük pazaryerlerinin sepetleri otomatik birleştirmesi.", "Kullanıcı istemediği ürünü sepette bulabilir."),
          O("son", "Son sepet kazanır", "Misafir sepeti eskisinin yerine geçer.", "Son eklenenin geçerli sayılması.", "Eski sepet kaybolur."),
      ],
      oneri=["sor"], goster={"soru": "U03", "iceren": "eticaret"},
      oneri_neden="Satın alma kararında sürpriz istenmez.",
      kaynak=["Keycloak raporu R4"], etkiler=["M21", "AT-24"]),

    S("K14", "kimlik", "P1", "sen",
      "Kullanıcı hesabını silmek isterse ne olsun?",
      "M6 hesap silmeyi Keycloak'a yönlendiriyor. Silmenin Frappe kullanıcısı, üyelikler, grant, Run ve kişisel çalışma alanı üzerindeki etkisi tanımlı değil.",
      [
          O("anonim", "Kimlik silinir, Frappe kullanıcısı anonimleştirilir, yasal kayıtlar anonim kalır",
            "Keycloak kimliği silinir. Frappe kullanıcısı anonimleştirilir; üyelikler, grant ve çalışan Run'lar kapanır. Yasal saklama gerektiren kayıtlar (ör. fatura) anonim kalır. Kullanıcıya sonuç özeti gösterilir.",
            "E-ticaret hesabını silince faturalarının yasal süre boyunca anonim saklanması.",
            "Silme orkestrasyonu, devre dışı bırakma gibi adım adım ve uzlaştırmalı yazılır."),
          O("destek", "Yalnız devre dışı bırakma; silme destek talebiyle",
            "Kullanıcı hesabını kapatır; kalıcı silme destek ekibinden istenir.",
            "Bazı abonelik sitelerinin \"hesabı silmek için bize yazın\" demesi.",
            "KVKK silme talebi süreçle karşılanır."),
          O("yok", "İlk sürümde hesap silme yok (açık kapsam dışı kararı)",
            "Silme özelliği sonraki sürüme kalır.",
            "Yeni açılan dükkânın iade politikasını sonra yazması.",
            "KVKK silme hakkı elle karşılanmak zorunda kalır."),
      ],
      oneri=["anonim"], oneri_neden="KVKK silme hakkını ürün içinde karşılar, yasal kayıtları da korur.",
      kaynak=["Codex D08"], etkiler=["M6", "M19", "G7"]),

    S("K15", "kimlik", "P1", "sen",
      "Bir şirketin son yöneticisi ayrılmak veya silinmek isterse ne olsun?",
      "Son yönetici giderse şirket yönetilemez hâle gelir; belge bu durumu tanımlamıyor.",
      [
          O("devret", "Son yönetici önce sahipliği devretmeden ayrılamaz",
            "Sistem son yöneticinin ayrılmasını engeller, devir ekranına yönlendirir.",
            "Kurumsal hesaplarda son süper yöneticinin silinememesi.",
            "Üyelik yaşam döngüsü tablosuna kural ve kabul deneyi eklenir."),
          O("destek", "Platform destek ekibi yeni yönetici atar",
            "Ayrılmaya izin verilir; destek sonradan kimlik doğrulayıp yönetici atar.",
            "Apartman yöneticisi taşınınca site yönetiminin yenisini ataması.",
            "Destek süreci ve kimlik doğrulama adımları yazılır."),
      ],
      oneri=["devret"], oneri_neden="Sahipsiz şirket hem güvenlik hem destek sorunu; önlemek daha ucuz. Acil durumlar için destek yolu ayrıca yazılabilir.",
      kaynak=["Codex D08"], etkiler=["M10", "M11"]),

    S("K16", "kimlik", "P2", "sen",
      "Müşteri şirket aboneliğini kapatırsa veri ne olsun?",
      "Organizasyon kapanışı için kullanıcı akışı ve kabul sonucu yok.",
      [
          O("30", "30 gün salt okunur ve dışa aktarım, sonra arşiv veya silme", "Müşteri verisini indirebilir.", "SaaS aboneliği iptalinde veri indirme süresi tanınması.", "Kapanış akışı ve bildirim e-postaları yazılır."),
          O("hemen", "Hemen silme", "Kapanışla birlikte veri silinir.", "Kiralık kasanın boşaltılması.", "Geri dönüş yok; yanlışlıkla kapanışta veri kaybı."),
          O("arsiv", "Süresiz arşiv", "Veri saklanır, erişim kapanır.", "Kapanan şirketin dosyalarının depoda durması.", "KVKK saklama ilkesiyle çelişir."),
      ],
      oneri=["30"], oneri_neden="Müşteriye hakkını verir, veriyi de süresiz tutmaz.",
      kaynak=["Codex D08"], etkiler=["M10", "G7"]),

    S("K17", "kimlik", "P2", "sen",
      "Ortak cihazda (kiosk) giriş nasıl olsun?",
      "Kiosk seçildi, ama kimlik bölümünde ortak cihazda hızlı kullanıcı değişimi ve passkey kullanımı tanımlı değil.",
      [
          O("kural", "Kısa boşta kalma, her değişimde tam temizlik, kişisel cihazla giriş",
            "2 dakika boşta kalınca oturum kapanır. Kullanıcı değişiminde önbellek ve taslak silinir. Giriş, cihazdaki passkey ile değil kullanıcının kendi telefonuyla yapılır.",
            "Hastanedeki ortak bilgisayarda her hemşirenin kendi kartıyla girmesi.",
            "Kimlik bölümüne ortak cihaz kuralları ve bir kabul deneyi eklenir."),
          O("yok", "Ortak cihaz desteklenmez; kişisel cihaz varsayılır",
            "Kiosk kapsam dışı kalır.",
            "Her çalışanın kendi dizüstünü kullanması.",
            "Karar kaydındaki kiosk seçimi kaldırılır."),
      ],
      oneri=["kural"], goster={"soru": "U12", "iceren": "kiosk"},
      oneri_neden="Kiosk gerçekten gerekiyorsa bu kurallar olmadan bir kişinin oturumu diğerine kalır.",
      kaynak=["Claude raporu E"], etkiler=["M6", "M25", "J6"]),

    S("K18", "kimlik", "P1", "teknik",
      "Keycloak sürümü ile yapılandırma aracının uyumsuzluğu nasıl çözülsün?",
      "Rehber Keycloak 26.7'yi seçiyor. Yapılandırmayı koddan uygulayan keycloak-config-cli'nin yayımlanmış son sürümü ise yalnız 26.5.5'e kadar test edilmiş.",
      [
          O("bekle", "26.7'de kal; uyum CI'da kanıtlanana kadar üretime çıkma",
            "Mevcut kural: CI'da uyum testi geçmeden canlı yok.",
            "Yeni işletim sistemine geçmeden bankacılık uygulamasının uyumunu beklemek.",
            "Uyum gelmezse takvim kayabilir."),
          O("geri", "Araçla uyumlu sürüme (26.5.x) sabitlen, uyum gelince 26.7'ye geç",
            "Önce uyumlu sürüm, sonra yükseltme.",
            "Yazıcı sürücüsü çıkana kadar eski işletim sisteminde kalmak.",
            "Eski sürümün güvenlik yamalarının sürdüğü doğrulanmalı."),
          O("baska", "Başka bir yapılandırma aracı",
            "Keycloak yapılandırması başka bir kod aracıyla yönetilir.",
            "Aynı işi yapan başka bir aleti almak.",
            "Yeni araç için öğrenme ve inceleme işi eklenir."),
      ],
      oneri=["bekle"], oneri_neden="Güvenlik yamaları en yeni sürümde. Uyum geç kalırsa ikinci seçeneğe geçilir.",
      kaynak=["Keycloak raporu (config-cli)", "Doğrulama"], etkiler=["M14", "M1"]),

    S("K19", "kimlik", "P1", "sen",
      "Frappe sosyal giriş kodundaki güvenlik bulgusu nasıl bildirilsin?",
      "Kimlik rehberi, bulgunun ayrıntısı herkese açık yazılmadan önce Frappe'nin güvenlik kanalına iletilmesini istiyor. Belge ayrıntıyı yazmıyor, ama bildirim henüz yapılmadı.",
      [
          O("taslak", "Claude bildirim taslağı hazırlar, sen gönderirsin",
            "Teknik metin hazır gelir, gönderen sen olursun.",
            "Avukatın dilekçe taslağını hazırlaması, senin imzalayıp göndermen.",
            "Yapılacaklar listesine tarihli bir madde girer."),
          O("sen", "Sen doğrudan yazarsın", "Metni kendin hazırlarsın.", "Dilekçeyi kendin yazmak.", "Teknik ayrıntı eksik kalabilir."),
          O("yok", "Bildirim yapılmaz", "Yalnız kendi köprümüz kullanılır.", "Apartmandaki arızayı görüp yönetime söylememek.", "Önerilmez; diğer Frappe kullanıcıları risk altında kalır."),
      ],
      oneri=["taslak"], oneri_neden="Sorumlu bildirim hem topluluğa hem sana güven kazandırır; teknik metin hazır olursa gönderim beş dakikalık iştir.",
      kaynak=["Keycloak raporu R10", "Kimlik rehberi"], etkiler=["M4", "Yapılacaklar"]),

    S("K20", "kimlik", "P1", "teknik",
      "Kapanan Keycloak bulgularının geri gelmesi nasıl önlensin?",
      "Keycloak raporundaki R1–R10 v2.4 ve v2.5'te kapatıldı. Belge her turda büyürken eski bir cümlenin geri gelmesi (ör. e-posta eşitliğiyle otomatik bağlama) kolaydır.",
      [
          O("regresyon", "Her kapanan bulgu için otomatik regresyon kontrolü ve kimlik değişikliklerinde K12 incelemesi",
            "Derleme betiği yasak ifadeleri ve zorunlu maddeleri denetler; yasak ifade geri gelirse veya zorunlu madde silinirse derleme kırılır. Kimlik değişikliklerinde K12 incelemesi yine yapılır.",
            "Aşı sonrası takip muayenesi: hastalık geçti diye kontrol bırakılmaz.",
            "Belge QA betiğine \"kapanan bulgular\" listesi eklenir."),
          O("insan", "Yalnız insan incelemesi",
            "Her değişiklikte gözle kontrol.",
            "Her gün evin tüm kapılarını tek tek kontrol etmek.",
            "Uzun belgede gözden kaçma olasılığı yüksek."),
      ],
      oneri=["regresyon"], oneri_neden="Ucuz, otomatik ve Keycloak raporunun kapanışını kalıcı yapar.",
      kaynak=["Keycloak raporu R1–R10", "Codex D15"], etkiler=["K12", "validate.py"]),

    S("K21", "kimlik", "P2", "sen",
      "Destek ekibi müşteri adına oturum açabilsin mi (vekil oturum)?",
      "Karar kaydı \"ayrı onayla sınırlı yazma\" seçmiş; önerisi \"vekil oturum yok\".",
      [
          O("yok", "Hayır; destek ekran paylaşımıyla yardım eder",
            "Destek ekibi müşterinin hesabına girmez.",
            "Banka müşteri temsilcisinin senin hesabına girememesi, ekranını paylaşman.",
            "G6'daki vekil oturum maddesi kaldırılır; güvenlik yüzeyi küçülür."),
          O("sinirli", "Evet; ayrı onaylı, süreli ve işaretli vekil oturum",
            "Müşteri onay verir, oturum süreli ve ekranda işaretlidir, YZ yazması kapalıdır.",
            "Teknik servisin senin onayınla bilgisayarına uzaktan bağlanması.",
            "G6 olduğu gibi kalır; ayrı onay ve denetim akışı geliştirilir."),
      ],
      oneri=["yok"], oneri_neden="Küçük ekipte vekil oturum hem geliştirme hem güvenlik yükü; ekran paylaşımı çoğu destek işini görür.",
      kaynak=["Karar kaydı: impersonation"], etkiler=["G6"]),

    # ------------------------------------------------------------------ VERİ VE SÖZLEŞME
    S("V01", "veri", "P1", "teknik",
      "Veriyi değiştiren her işlem aynı kapıdan mı geçsin?",
      "Belge bir yerde \"her yazma capability çağrısıdır\" diyor, başka bir yerde klasik kaydet ve submit için doğrudan Frappe REST yolunu da sözleşmeye koyuyor. Tekrar koruması, risk sınıfı ve denetim kaydının her yolda aynı olup olmadığı buna bağlı.",
      [
          O("tek", "Evet; klasik kaydet dahil her yazma platformun yürütücüsünden geçer",
            "Kullanıcı, YZ veya ajan: hepsi aynı kapıyı kullanır.",
            "Mağazadaki tüm ödemelerin tek kasadan geçmesi: fiş, stok ve kamera kaydı her ödemede aynı.",
            "Yazma yolu tablosu tek satıra iner; yürütücü her DocType için genel kaydet ve submit sunar."),
          O("iki", "Hayır; klasik kaydet doğrudan Frappe'ye, yalnız YZ ve onaylı değişiklik yürütücüden",
            "İki ayrı yazma yolu olur.",
            "Mağazanın yanında ayrı bir yan kapıdan da satış yapılması.",
            "Tekrar koruması ve denetim iki yolda ayrı ayrı sağlanmalı."),
      ],
      oneri=["tek"], oneri_neden="Tek kapı; denetimi, tekrar korumasını ve risk hesabını tek yerde toplar.",
      kaynak=["Uygulanabilirlik incelemesi 3"], etkiler=["B1", "D4", "F6", "F8", "G5"]),

    S("V02", "veri", "P1", "sen",
      "Aktif şirket bilgisi nasıl taşınsın?",
      "Birden fazla şirkete üye kullanıcı iki sekmede iki şirkette çalışırsa ne olacağı yazmıyor.",
      [
          O("istek", "Her istekte açıkça taşınır; her sekme kendi şirketinde çalışabilir",
            "Her sekmede hangi şirkette olduğun ekranda açıkça görünür; sunucu her istekte üyeliği doğrular.",
            "Tarayıcıda iki sekmede iki ayrı e-posta hesabı açmak.",
            "Mali müşavir gibi çok şirketli kullanıcılar için rahat; şirket göstergesi her ekranda zorunlu."),
          O("oturum", "Oturumda tek aktif şirket; değişince tüm sekmeler uyarılır",
            "Bir sekmede şirket değişirse diğerleri yenilenmek zorunda kalır.",
            "Mobil bankacılıkta aynı anda tek hesaba bakmak.",
            "Basit ama çok şirketli çalışma zorlaşır."),
      ],
      oneri=["istek"], oneri_neden="Yanlış şirkete yazma riskini sunucu doğrulaması ve görünür şirket göstergesi önler; çok şirketli iş akışı da korunur.",
      kaynak=["Uygulanabilirlik incelemesi 2"], etkiler=["B9", "M10", "M22"]),

    S("V03", "veri", "P1", "sen",
      "Paylaşılan rapor ve görünümlerdeki gizli filtre değerleri nasıl korunsun?",
      "D7 UI tanımının iş verisi taşımadığını söylüyor, ama filtre değerleri (müşteri adı, vergi numarası, tutar) tanımın içinde duruyor. Tanım paylaşılınca bu değerler de gider.",
      [
          O("referans", "Filtre değerleri sunucuda yetkili bir \"kayıtlı sorgu\"da durur",
            "Paylaşılan kişi sonucu kendi yetkisiyle görür, gizli değerleri göremez.",
            "Paylaşılan bir klasörde karşı tarafın yalnız yetkili olduğu dosyaları görmesi.",
            "D6, D7 ve G7'ye kayıtlı sorgu ve paylaşım kuralı eklenir."),
          O("maske", "Paylaşımda filtre değerleri maskelenir",
            "Paylaşılan tanımda değerler \"***\" olarak görünür.",
            "Ekran görüntüsünde isimlerin karartılması.",
            "Maskeli filtreyle rapor anlamını kaybedebilir."),
          O("ayni", "Tanım yalnız aynı yetkideki kişilerle paylaşılabilir",
            "Paylaşım yetki eşitliğine bağlanır.",
            "Gizli toplantı notunun yalnız katılımcılara gitmesi.",
            "Basit ama paylaşım kullanışsızlaşır."),
      ],
      oneri=["referans"], oneri_neden="Hem paylaşımı kullanışlı tutar hem gizli değeri korur.",
      kaynak=["Codex D07"], etkiler=["D6", "D7", "G7"]),

    S("V04", "veri", "P1", "sen",
      "Kullanıcı \"bu konuşmayı unut\" veya \"sil\" deyince ne silinsin?",
      "Silmenin bağlam önbelleği, saklı öneri, vektör indeksi, denetim kaydı ve yedeklerdeki etkisi tanımlı değil.",
      [
          O("tam", "Sohbet, önbellek, öneri ve indeks hemen; yedekler en geç 35 günde; denetimde yalnız olay kalır",
            "İçerik her yerden silinir; denetim kaydında \"kim, ne zaman sildi\" bilgisi kalır, içerik kalmaz.",
            "Hesabını silince verinin yedeklerden de belirli sürede temizlenmesi.",
            "G7'ye veri yaşam döngüsü tablosu eklenir: nesne, amaç, erişen, saklama, silme tetikleyicisi."),
          O("sohbet", "Yalnız sohbet metni silinir",
            "Türetilmiş kopyalar kalır.",
            "Mektubu yakmak ama fotokopisini dosyada bırakmak.",
            "\"Unut\" dendikten sonra model silinen içeriği yine kullanabilir."),
      ],
      oneri=["tam"], oneri_neden="Kullanıcıya verilen \"unut\" sözünün gerçekten tutulması.",
      kaynak=["Codex D07"], etkiler=["I8", "I9", "G7"]),

    S("V05", "veri", "P1", "teknik",
      "İki iş aynı anda aynı yetki bütçesini kullanırsa ne olsun?",
      "E7 aynı anda iki Run'a izin veriyor; F3 grant için toplam kayıt ve maliyet bütçesi tanımlıyor. Ama iki Run'ın aynı bütçeyi aynı anda tüketmesi tanımsız.",
      [
          O("rezerv", "Bütçe her adımdan önce atomik olarak ayrılır (rezervasyon)",
            "İki Run aynı anda toplamı aşamaz. Sonucu bilinmeyen işlem rezervasyonu serbest bırakmaz; grant iptaliyle yarışta iptal kazanır.",
            "Şirket kartında iki çalışan aynı anda harcasa da bankanın limiti aşmaması.",
            "F3'e rezervasyon, tüketim ve serbest bırakma kuralı; AT'ye paralel Run senaryosu eklenir."),
          O("ayri", "Her Run kendi sınırında; grant toplamı yok",
            "Bütçe yalnız Run başına sayılır.",
            "Her çalışana ayrı nakit avans vermek.",
            "Toplam harcama kontrol edilemez."),
      ],
      oneri=["rezerv"], oneri_neden="Grant bir üst sınırsa, eşzamanlı işte de üst sınır olarak kalmalı.",
      kaynak=["Codex D05"], etkiler=["F3", "E7"]),

    S("V06", "veri", "P1", "teknik",
      "Uzun iş çalışırken sunucu çökerse ne olsun?",
      "E10 kaldığı yerden devam ve \"outcome_unknown\" tanımlıyor. Ama çalışanın dış çağrıdan önce mi, dış işlem gerçekleştikten sonra mı, yoksa sonuç kaydedilmeden mi öldüğü ayrılmıyor. Süresi dolmuş eski çalışanın yazmaya devam etmesi de engellenmiyor.",
      [
          O("gunluk", "Adım günlüğü niyet → gönderildi → sonuç; belirsiz sonuç tekrarlanmaz, uzlaştırmaya gider",
            "Sonucu bilinmeyen dış işlem otomatik tekrar edilmez. Süresi dolan eski çalışan sahiplik numarasıyla reddedilir. Dış sağlayıcı tekrar korumasını destekliyorsa aynı anahtarla güvenli tekrar yapılır.",
            "Havale zaman aşımına uğrarsa tekrar göndermeden önce hesap hareketine bakmak.",
            "E10'a durum geçiş tablosu, AT-17'ye ayrı çöküş anları eklenir."),
          O("tekrar", "Son tamamlanan adımdan otomatik tekrar",
            "Basit yeniden deneme.",
            "Cevap gelmeyince havaleyi tekrar göndermek.",
            "Aynı işlem iki kez yapılabilir (ör. iki e-posta, iki ödeme)."),
      ],
      oneri=["gunluk"], oneri_neden="\"Tek yan etki\" sözü ancak belirsiz sonucu tekrar etmemekle tutulabilir.",
      kaynak=["Codex D06"], etkiler=["E10", "F6", "AT-17"]),

    S("V07", "veri", "P1", "teknik",
      "Sözleşmelerin (veri yapılarının) tek kaynağı ne olsun?",
      "Şema kaynağı frontend deposunda (zod, TypeScript); doğrulama ve göç ise Python sunucuda. Hangi dosyanın asıl olduğu tanımsız.",
      [
          O("zod", "zod (TypeScript) asıl kaynak; JSON Schema sürümlü paket olarak üretilir, Python onu kullanır",
            "Her yapının geçerli ve geçersiz örneği CI'da sınanır.",
            "Tek bir teknik şartname; iki fabrika aynı şartnameden üretir.",
            "Mevcut belgeyle en az değişiklik; sözleşme hattı bölümü eklenir."),
          O("json", "JSON Schema asıl kaynak; zod ve Python modeli ondan üretilir",
            "Dilden bağımsız tek kaynak.",
            "Çeviriye kaynak metin olarak üçüncü bir dil kullanmak.",
            "Tarafsız ama iki yönde üretim aracı gerekir."),
          O("python", "Python (Pydantic) asıl kaynak",
            "Sunucu tarafı asıl olur.",
            "Şartnameyi sadece bir fabrikanın dilinde yazmak.",
            "Frontend tipleri Python'dan üretilir; belge baştan değişir."),
      ],
      oneri=["zod"], oneri_neden="Belgede zaten zod kaynağı var; en az değişiklikle tek kaynak kuralı kurulur.",
      kaynak=["Uygulanabilirlik incelemesi 8", "Claude raporu B8"], etkiler=["D1", "D8", "K1", "B2"]),

    S("V08", "veri", "P1", "sen",
      "Geliştirmeden önce ilk akışın örnekli sözleşme paketi yazılsın mı?",
      "UI Spec, capability manifesti, ChangeSet, Grant, Run ve filtre yapısı yalnız adıyla anılıyor. Üç ekip (frontend, Frappe, model) aynı örneği okumadan başlarsa her biri kendi şemasını uydurur.",
      [
          O("once", "Evet; ilk akış için örnekli sözleşme paketi ve Run durum tablosu önce yazılır",
            "Manifest → istek → öneri → onay → sonuç (başarı, kısmi başarı, çakışma) → görünüm. Zorunlu, istemcinin gönderdiği ve sunucunun türettiği alanlar ayrı işaretlenir; geçerli ve geçersiz örnekler eklenir.",
            "İnşaattan önce statik projenin çizilmesi.",
            "Belgeye \"Sözleşme eki\" eklenir; geliştirme bu ekten başlar."),
          O("sonra", "Hayır; geliştirme sırasında ortaya çıksın",
            "Kod yazıldıkça şema belirlenir.",
            "Evi yaparken planı çizmek.",
            "Ekipler arası uyumsuzluk ve yeniden yazma riski."),
      ],
      oneri=["once"], oneri_neden="Senin kuralın da bu: önce test, sonra veri şeması, sonra geliştirme.",
      kaynak=["Codex D04", "Uygulanabilirlik incelemesi 1", "Claude raporu B1"], etkiler=["H1", "D1", "F3", "E5"]),

    S("V09", "veri", "P1", "sen",
      "Platformun kendi Frappe tabloları (DocType) geliştirmeden önce modellensin mi?",
      "Run, ChangeSet, Grant, onay kaydı, tekrar koruması, denetim, çalışma kopyası, marka paketi ve kimlik tabloları için alan, bağlantı, izin, indeks ve saklama tanımı yok.",
      [
          O("once", "Evet; Platform DocType kataloğu geliştirmeden önce",
            "Her tablo için alanlar, tipler, bağlantılar, izin kuralları, benzersiz indeksler, saklama süresi ve sahibi olan uygulama yazılır.",
            "Mimarın binayı çizmeden önce oda listesini ve ölçülerini çıkarması.",
            "Belgeye DocType kataloğu eki girer; kimlik tabloları rehberden alınıp sabitlenir."),
          O("sonra", "Geliştirme ilerledikçe",
            "Tablolar ihtiyaç çıktıkça eklenir.",
            "Odaları yaşarken eklemek.",
            "Göç ve veri düzeltme işi artar."),
      ],
      oneri=["once"], oneri_neden="Veri şeması değişikliği en pahalı değişikliktir; önce yazmak ucuzdur.",
      kaynak=["Uygulanabilirlik incelemesi 5", "Claude raporu B5"], etkiler=["E2", "E5", "E10", "F1", "F3", "F6", "G5", "M5"]),
]
