"""Karar kitabı soru bankası, bölüm 1-3: ürün ve kapsam, belgedeki çelişkiler, YZ öncelikli deneyim.

Her soru S(...) ile, her seçenek O(...) ile tanımlanır. Alanların anlamı build_karar.py içinde yazılıdır.
"""
from ortak import S, O

SORULAR = [
    # ------------------------------------------------------------------ ÜRÜN VE KAPSAM
    S("U01", "urun", "P1", "sen",
      "Ana proje bugün hangi durumda?",
      "Belgedeki Desk eşitliği, tek kesim geçiş, Client Script envanteri ve Desk'e dönüş provası gibi maddeler, bugün Frappe Desk'i kullanan gerçek kullanıcılar olduğu varsayımıyla yazıldı. Sıfırdan başlayan bir üründe bu maddeler aylarca gereksiz iş demektir.",
      [
          O("canli", "Canlıda Frappe veya ERPNext Desk'i kullanan kullanıcılar var",
            "Yeni arayüz, insanların her gün kullandığı mevcut ekranların yerine geçecek.",
            "Bir toptancı yıllardır ERPNext kullanıyor; depo ekibi her sabah Desk'te stok girişi yapıyor.",
            "Desk eşitliği (parity), geçiş provası ve Desk'e dönüş planı zorunlu kalır."),
          O("pilot", "Frappe kurulu ama gerçek kullanıcı yok (pilot, test)",
            "Kurulum ve veri modeli var, kullanıcılar henüz alışkanlık edinmedi.",
            "Kurulum yapılmış, ekip test verisiyle deniyor; müşteri henüz sisteme girmedi.",
            "Eşitlik matrisi hafifler; geçiş provaları pilot kullanıcılarla yapılır."),
          O("sifir", "Sıfırdan: ürün henüz yok",
            "İlk müşteriler doğrudan yeni arayüzle başlayacak.",
            "Yeni bir SaaS girişimi; ilk müşteri hiç Desk görmeden yeni panele giriş yapacak.",
            "Desk eşitliği ve tek kesim geçiş maddeleri kaldırılır ya da \"yalnız sistem yönetimi için Desk\" diye daralır; çok zaman kazandırır."),
      ],
      oneri=None,
      oneri_neden="Bu bilgi sende; doğru cevap projenin gerçek durumudur. Diğer birçok sorunun önerisi bu cevaba göre değişir.",
      kaynak=["Claude raporu D1", "Karar kaydı: migration, parity, scripts"],
      etkiler=["B4", "B8", "K7", "AT-10"]),

    S("U02", "urun", "P1", "sen",
      "\"AEP\" nedir?",
      "Belgede @aep/ui, \"AEP markası\" ve \"AEP token'ları\" geçiyor ama AEP hiçbir yerde tanımlanmıyor. Giriş ekranı, e-postalar ve alan adları bu isme göre kurulacak.",
      [
          O("kod", "AEP geçici bir kod adı; gerçek marka sonra belirlenecek",
            "Paket ve token adları AEP kalır, kullanıcının gördüğü marka ayrı bir değişkenden gelir.",
            "Büyük şirketler ürünleri geliştirirken kod adı kullanır; ürün çıkarken gerçek adını alır.",
            "Belgeye \"AEP: ürün ailesinin kod adı\" tanımı girer; marka adı white-label paketinde ayrı alan olur."),
          O("marka", "AEP gerçek marka adı",
            "Kullanıcıların giriş ekranında ve e-postalarda göreceği ad AEP'dir.",
            "Bir ürünün adının hem kodda hem müşteri ekranında aynı olması.",
            "Giriş ekranı, e-posta gönderici adı ve alan adları AEP ile kurulur."),
          O("baska", "Başka bir ad kullan (not alanına yaz)",
            "Paket ve marka adı başka bir isimle değiştirilir.",
            "Proje ortasında markanın netleşmesi ve kodun yeni adla güncellenmesi.",
            "@aep/ui paket adı ve belge terimleri yeni adla değişir."),
      ],
      oneri=["kod"],
      oneri_neden="Marka kararı teknik kararları beklemesin diye paket adını sabit tutmak, kullanıcıya görünen adı ayrı yönetmek en esnek yol.",
      kaynak=["Claude raporu G2"], etkiler=["C1", "M7", "M13"], serbest=True),

    S("U03", "urun", "P1", "sen",
      "Ürün ailesinde hangi uygulamalar olacak?",
      "Belge örneklerini ürün bilgisi (katalog) üzerinden anlatıyor; kimlik rehberi ise /crm ve /muhasebe gibi uygulamalardan söz ediyor. Her uygulama farklı risk kuralları ister: muhasebe verisi finansal, CRM verisi kişiseldir.",
      [
          O("panel", "Yönetim paneli ve sistem ayarları",
            "Kullanıcı, rol, şirket ve genel ayar ekranları.",
            "Her SaaS ürünündeki \"Ayarlar\" ve \"Kullanıcılar\" sayfaları.",
            "Temel kabuk ve yetki ekranları ilk teslimde yer alır."),
          O("pim", "Ürün bilgisi ve katalog (PIM)",
            "Ürün özellikleri, varyantlar, görseller ve tedarikçi belgeleri.",
            "Bir e-ticaret kataloğunda 5.000 ürünün renk, beden, malzeme bilgisini yönetmek.",
            "Belgedeki varsayılan YZ yolculuğu bu alana uyar."),
          O("crm", "Müşteri ilişkileri (CRM)",
            "Müşteri kartları, fırsatlar, görüşme notları.",
            "Satış ekibinin müşteri görüşmelerini ve tekliflerini takip ettiği ekranlar.",
            "Kişisel veri \"sensitive\" sınıfındadır; YZ yazmaları her seferinde onay ister, KVKK kuralları ağırlaşır."),
          O("muhasebe", "Muhasebe ve finans",
            "Fatura, gider, cari hesap, vergi.",
            "Muhasebecinin gelen faturaları sisteme girip KDV beyannamesine hazırlaması.",
            "Finansal veri \"sensitive\" sınıfındadır; e-Fatura, e-Arşiv, e-Defter gibi yasal belgeler için ayrı kural gerekir."),
          O("eticaret", "E-ticaret (www: hesap, sepet, ödeme)",
            "Herkese açık site, müşteri hesabı, sepet ve ödeme.",
            "Bir markanın kendi sitesinden ürün satması.",
            "www hesap ve misafir sepeti sözleşmesi (M21) ve ödeme entegrasyonu gündeme girer."),
          O("ik", "İnsan kaynakları",
            "Personel kartı, izin, bordro verisi.",
            "Çalışanların izin talebi ve yöneticinin onayı.",
            "Özel nitelikli kişisel veri (sağlık raporu gibi) içerebilir; en sıkı veri sınıfı kuralları uygulanır."),
          O("destek", "Destek ve talep yönetimi",
            "Müşteri talepleri, çağrı kayıtları, çözüm süreleri.",
            "Bir yazılım firmasının destek masası.",
            "Frappe Helpdesk AGPL lisanslıdır; kod kopyalanmaz, yalnız davranış tarif edilir."),
          O("icerik", "İçerik yönetimi (Drupal)",
            "Blog, kampanya ve kurumsal sayfalar.",
            "Pazarlama ekibinin kampanya sayfası yayımlaması.",
            "Drupal ayrı Keycloak istemcisi olarak bağlanır; tek oturum ve tek çıkış kapsamına girer."),
      ],
      tip="cok", oneri=None,
      oneri_neden="Ürün ailesini sen belirlersin. Seçtiğin her uygulama ilgili risk ve veri kurallarını belgeye ekletir.",
      kaynak=["Claude raporu D1", "AI-first incelemesi 3"], etkiler=["F2", "M23", "M21"], serbest=True),

    S("U04", "urun", "P1", "sen",
      "İlk canlıya çıkacak iş (ilk dikey dilim) hangi alanda olsun?",
      "Belgenin varsayılan yolculuğu \"seçili ürünlerin eksik özniteliklerini tedarikçi belgelerinden tamamla\" görevi üzerine kurulu. Bu görev senin ürün ailen için doğru ilk adım mı, karar ver.",
      [
          O("katalog", "Ürün bilgisi: eksik alanları belgelerden tamamlama",
            "YZ tedarikçi belgesinden eksik ürün bilgilerini önerir, kullanıcı onaylar.",
            "500 ürünün malzeme ve ölçü bilgisini tedarikçi PDF'lerinden doldurmak; eskiden bir kişinin bir haftası gidiyordu.",
            "Mevcut yolculuk ve kabul deneyleri (AT-13, AT-14) aynen kalır."),
          O("rapor", "Rapor: doğal dilden rapor (yalnız okuma)",
            "Kullanıcı sorusunu yazar, sistem raporu kurar; hiçbir kayıt değişmez.",
            "\"Geçen ay en çok iade edilen 10 ürün\" diye yazıp tabloyu görmek.",
            "Risk en düşüktür, ama YZ'nin yazma değeri bu dilimde kanıtlanmaz."),
          O("crm", "CRM: müşteri kayıtlarını temizleme ve zenginleştirme",
            "YZ yinelenen müşteri kayıtlarını bulur, birleştirme önerir.",
            "Aynı firmanın üç farklı yazımla kayıtlı olduğunu bulup tek karta indirmek.",
            "Kişisel veri nedeniyle her değişiklik açık onay ister; KVKK maddeleri ilk dilime girer."),
          O("muhasebe", "Muhasebe: gelen faturadan kayıt taslağı",
            "YZ fatura PDF'inden gider kaydı taslağı hazırlar.",
            "Aylık 300 tedarikçi faturasının elle girilmesi yerine taslakların kontrol edilmesi.",
            "En yüksek risk: finansal ve yasal kayıt. İlk dilim olarak önerilmez."),
      ],
      oneri=["katalog"],
      oneri_neden="Geri alınabilir, kişisel veri içermeyen ve değeri ölçülebilen bir iş. Ürün ailende katalog yoksa \"rapor\" seçeneği en güvenli başlangıçtır.",
      kaynak=["AI-first incelemesi 3", "Codex D13"], etkiler=["Varsayılan yolculuk", "AT-13", "AT-14"], serbest=True),

    S("U05", "urun", "P1", "sen",
      "İlk teslimin birincil kullanıcısı kim?",
      "Belge \"her personanın ilk üç görevi\" ve \"3 persona × 5 kullanıcı\" diyor ama persona tanımı yok. Karar kaydı dört kullanıcı kitlesi seçmiş. İlk teslim tek bir ana kullanıcıya göre tasarlanmalı.",
      [
          O("operasyon", "Operasyon ekibi",
            "Gün boyu kayıt giren, güncelleyen, onaylayan kişiler.",
            "Katalog sorumlusunun her gün yüzlerce ürün kaydını düzeltmesi.",
            "Hız, klavye kullanımı, toplu işlem ve yoğun listeler öne çıkar."),
          O("analist", "Analist ve yönetici",
            "Rapor okuyan, karşılaştıran, karar veren kişiler.",
            "Satış müdürünün haftalık performans raporuna bakması.",
            "Rapor, grafik ve doğal dilden rapor özellikleri öne çıkar."),
          O("musteri", "Müşteri veya iş ortağı (portal)",
            "Şirket dışından, kendi kayıtlarını gören kullanıcılar.",
            "Bayinin kendi siparişlerini ve faturalarını görmesi.",
            "Portal, dış kullanıcı kimliği ve KYC/KYB akışları öne çıkar."),
          O("yonetici", "Sistem yöneticisi",
            "Kullanıcı, rol ve ayarları yöneten kişi.",
            "BT sorumlusunun yeni çalışana yetki vermesi.",
            "Ayar ve yetki ekranları öne çıkar; YZ değeri daha sınırlıdır."),
      ],
      oneri=["operasyon"],
      oneri_neden="Karar kaydının önerisi operasyon ve analist. YZ'nin en çok zaman kazandırdığı yer tekrarlı kayıt işidir.",
      kaynak=["Claude raporu D1", "Codex D10", "Karar kaydı: audience"], etkiler=["AT-13", "J1", "J6"]),

    S("U06", "urun", "P2", "sen",
      "İlk teslimde desteklenecek ikincil kullanıcılar kimler?",
      "Birincil kullanıcının yanında ilk sürümde hangi kullanıcıların da işini bitirebilmesi gerektiğini seç.",
      [
          O("operasyon", "Operasyon ekibi", "Kayıt giren ve güncelleyen kullanıcılar.", "Depo veya katalog ekibi.", "Liste ve form ekranları kapsamda kalır."),
          O("analist", "Analist ve yönetici", "Rapor ve karar kullanıcıları.", "Satış müdürü.", "Rapor ve grafik ekranları kapsamda kalır."),
          O("musteri", "Müşteri veya iş ortağı", "Portal kullanıcıları.", "Bayi.", "Portal ve dış kimlik akışları ilk sürüme girer."),
          O("yonetici", "Sistem yöneticisi", "Ayar ve yetki kullanıcıları.", "BT sorumlusu.", "Yetki ekranları ilk sürüme girer."),
      ],
      tip="cok", oneri=["analist", "yonetici"],
      oneri_neden="Analist raporu, yönetici de yetkileri yönetir; ikisi olmadan ilk teslim kullanılabilir olmaz. Portal sonraki faza kalabilir.",
      kaynak=["Karar kaydı: audience, surface"], etkiler=["L8", "M11"]),

    S("U07", "urun", "P1", "sen",
      "Muhasebe ve finans alanında YZ ne yapabilsin?",
      "Finansal veri belgede \"sensitive\" sınıfında. Yasal belgeler (e-Fatura, e-Arşiv, e-Defter) geri alınamaz ve cezai sonucu olabilir.",
      [
          O("okuma", "Yalnız okuma ve açıklama",
            "YZ rakamları açıklar, hiçbir kaydı değiştirmez.",
            "\"Bu ay KDV neden arttı?\" sorusuna faturaları göstererek cevap vermesi.",
            "Muhasebede YZ yazma yeteneği hiç açılmaz."),
          O("taslak", "Taslak üretir, insan kontrol edip kaydeder",
            "YZ kayıt taslağı hazırlar; muhasebeci kontrol eder, kendisi kaydeder.",
            "Banka uygulamasının harcamanı kategorize etmesi ama para transferini senin onaylaman.",
            "Taslaklar ayrı çalışma kopyasında durur; yasal belge gönderimi YZ'ye hiç açılmaz."),
          O("tam", "Onaylı kayıt ve yasal belge gönderimi dahil",
            "YZ onaydan sonra kaydı yapar ve e-Fatura gibi yasal belgeyi gönderir.",
            "Otomatik pilotun iniş yapması: mümkün ama çok yüksek güvence ister.",
            "Önerilmez; yasal ve mali sorumluluk YZ akışına bağlanır."),
      ],
      oneri=["taslak"], goster={"soru": "U03", "iceren": "muhasebe"},
      oneri_neden="Değer taslakta, risk yasal gönderimde. Taslak modeli ikisini ayırır.",
      kaynak=["AI-first incelemesi 3"], etkiler=["F2", "M23"]),

    S("U08", "urun", "P2", "sen",
      "Frappe v15 desteklenecek mi?",
      "Belge v15'i \"paralel bakımda\" diye anıyor, ama güvenlik mekanizmaları yalnız v16.35.0 kaynak kodunda doğrulandı. İki sürüm desteklemek her kontrolü ikiye katlar.",
      [
          O("v16", "Yalnız v16",
            "Tüm kurulumlar v16 ve üstü olur.",
            "Bir mobil uygulamanın yalnız son iki iOS sürümünü desteklemesi.",
            "Test ve doğrulama yükü yarıya iner; v15 fixture'ları kaldırılır."),
          O("ikisi", "v15 ve v16",
            "İki sürüm için ayrı sözleşme testleri tutulur.",
            "Bir web sitesinin hem eski hem yeni tarayıcıyı desteklemesi.",
            "Oturum, workflow ve realtime güvenceleri v15 kaynağında ayrıca doğrulanır."),
          O("envanter", "Mevcut kurulum envanterine göre karar",
            "Önce hangi sürümlerin kullanımda olduğu çıkarılır.",
            "Taşınmadan önce evdeki eşyaların listesini çıkarmak.",
            "Karar faz 00 keşfine bağlanır."),
      ],
      oneri=["v16"],
      oneri_neden="Sıfırdan veya pilot durumdaysan yalnız v16 en az iştir. Canlıda v15 kullanan müşteri varsa \"envanter\" seç.",
      kaynak=["Uygulanabilirlik incelemesi 15"], etkiler=["A3", "F8", "M25", "B6"]),

    S("U09", "urun", "P1", "sen",
      "İlk teslimde müşteriler hangi markayı görsün (white-label seviyesi)?",
      "Belge üç seviye tanımlıyor ve yalnız seviye 1'i bağlayıcı yapıyor. Müşteri markalı ürün bekleniyorsa bunun ilk teslime girip girmediği açıkça seçilmeli.",
      [
          O("s1", "Seviye 1: yalnız ürün markası",
            "Herkes aynı ürün markasını görür.",
            "Bir pazaryerinin satıcı paneli: her satıcı aynı paneli görür.",
            "En az iş; tek tema, tek e-posta şablonu."),
          O("s2", "Seviye 2: müşteri markası, platform alan adında",
            "Müşterinin logosu, adı ve rengi görünür; adres platformun alan adıdır.",
            "Kurumsal mesajlaşma aracında şirketinin logosunun görünmesi, adresin değişmemesi.",
            "Tenant modeli kararına bağlıdır; giriş, hesap ve e-posta için ayrı marka çözümleme gerekir."),
          O("s3", "Seviye 3: müşterinin kendi alan adı",
            "Müşteri kendi alan adında (ör. panel.musteri.com) çalışır.",
            "E-ticaret altyapısında mağazanın kendi alan adıyla açılması.",
            "Alan adı başına TLS, müşteri başına Keycloak realm'i, Google ve Apple kayıtları; enterprise iş yükü."),
      ],
      oneri=["s1"],
      oneri_neden="Seviye 2 tenant kararını, seviye 3 ağır işletim altyapısını gerektirir. İlk teslimde seviye 1 ile başlayıp talebe göre yükselmek en güvenli yol.",
      kaynak=["Codex D13", "Keycloak raporu R5"], etkiler=["M13", "K11"]),

    S("U10", "urun", "P2", "sen",
      "Ürün nasıl dağıtılacak?",
      "Dağıtım modeli, AGPL ve GPL lisanslı Frappe uygulamalarından doğan yükümlülükleri ve seviye 3 white-label'in gerekip gerekmediğini belirler.",
      [
          O("saas", "Yalnız SaaS (biz barındırırız)",
            "Müşteri ürünü tarayıcıdan kullanır; kod müşteriye verilmez.",
            "Muhasebe veya CRM'i bulutta abonelikle kullanmak.",
            "Lisans yükümlülükleri en hafif hâlindedir; AGPL koddan kopyalama yasağı yine geçerlidir."),
          O("kurulum", "Müşterinin sunucusuna kurulum",
            "Ürün müşterinin kendi altyapısında çalışır.",
            "Bir bankanın yazılımı kendi veri merkezine kurdurması.",
            "Lisans, sürüm ve destek yükü artar; her müşteri ayrı ortamdır."),
          O("ikisi", "İkisi birden",
            "Varsayılan SaaS, büyük müşteriye kurulum.",
            "Bulut sürümü olan ama kurumsal müşteriye kurulum da yapan yazılımlar.",
            "İki dağıtım hattı ve iki destek modeli gerekir."),
      ],
      oneri=["saas"],
      oneri_neden="Tek ekip için en sürdürülebilir model. Kurulum ihtiyacı doğarsa ayrıca planlanır.",
      kaynak=["Kimlik rehberi açık kararı: ticari dağıtım"], etkiler=["A5"]),

    S("U11", "urun", "P2", "sen",
      "İlk yıl beklenen ölçek nedir?",
      "Karar kaydı \"yoğun veri ve analitik\" seçmiş, önerisi \"önce ölçelim\". Ölçek; ileri grid, sanallaştırma ve performans bütçelerinin ne kadar sıkı olacağını belirler.",
      [
          O("kucuk", "Küçük: 50'den az eşzamanlı kullanıcı, DocType başına 100 binden az kayıt",
            "Tek şirket veya birkaç küçük müşteri.",
            "20 kişilik bir ekibin günlük operasyonu.",
            "Standart liste ve form yeterli; ileri grid ertelenir."),
          O("orta", "Orta: 50–500 eşzamanlı kullanıcı, 1 milyon kayda kadar",
            "Birkaç orta ölçekli müşteri.",
            "Bölgesel bir dağıtım şirketinin tüm şubeleri.",
            "Sunucu tarafı sayfalama ve sanallaştırma zorunlu."),
          O("buyuk", "Büyük: 500'den fazla eşzamanlı kullanıcı, milyonlarca kayıt",
            "Yoğun veri ve analitik.",
            "Ulusal bir perakende zincirinin tüm ürün ve stok verisi.",
            "İleri grid, pivot ve analitik yüzey ilk planlara girer."),
          O("olc", "Bilmiyorum; önce ölçelim",
            "Pilotta gerçek kullanım ölçülür, bütçeler sonra sıkılaştırılır.",
            "Yeni bir restoranın ilk ay müşteri sayısını görüp kadroyu ona göre kurması.",
            "Performans bütçeleri başlangıç değerleriyle kalır; ölçümle güncellenir."),
      ],
      oneri=["olc"],
      oneri_neden="Karar kaydının kendi önerisi. Tahminle büyük ölçeğe göre kurmak erken maliyettir.",
      kaynak=["Karar kaydı: scale, user-scale"], etkiler=["K3", "L7", "D5"]),

    S("U12", "urun", "P2", "sen",
      "Hangi cihazlarda iş yapılacak?",
      "Karar kaydı dört cihaz sınıfı seçmiş (masaüstü, tablet, telefon, kiosk); önerisi masaüstü ve telefon. Kiosk (ortak cihaz) kimlik kurallarını değiştirir.",
      [
          O("masaustu", "Masaüstü ve dizüstü", "Ofis bilgisayarı.", "Muhasebecinin iki ekranlı masası.", "Ana tasarım hedefi."),
          O("tablet", "Tablet ve saha", "Depo veya sahada tablet.", "Depo sayım ekibinin tabletle stok sayması.", "Dokunma hedefleri ve yatay ekran testleri zorunlu."),
          O("telefon", "Telefon", "Yolda kısa işler.", "Yöneticinin telefondan onay vermesi.", "320 px ve dar ekran kabulleri zorunlu."),
          O("kiosk", "Kiosk veya ortak terminal", "Birden fazla kişinin kullandığı ortak cihaz.", "Fabrika girişindeki ortak terminal veya mağaza kasası.", "Ortak cihaz kimlik kuralları (K17) devreye girer."),
      ],
      tip="cok", oneri=["masaustu", "telefon"],
      oneri_neden="Karar kaydının önerisi. Tablet ve kiosk ancak gerçek bir saha veya ortak cihaz işi varsa eklenmeli.",
      kaynak=["Karar kaydı: devices", "Claude raporu E"], etkiler=["J1", "J6", "D10"]),

    # ------------------------------------------------------------------ ÇELİŞKİLER
    S("C01", "celiski", "P1", "sen",
      "Toplu güncellemenin risk sınıfı ne olsun?",
      "F2 toplu güncellemeyi \"destructive\" sayıyor; F3'e göre bu sınıf için grant verilemez, her seferinde açık onay gerekir. Aynı belgede varsayılan yolculuk ve BulkEdit bileşeni aynı işi \"safe write\" sayıyor ve grant ile onaysız uyguluyor.",
      [
          O("hep", "Her toplu güncelleme destructive: her seferinde açık onay",
            "Kaç kayıt olursa olsun toplu değişiklik tek tek onaylanır; grant verilemez.",
            "Şirket bankacılığında toplu ödeme talimatının her seferinde imza istemesi.",
            "En güvenlisi, ama onay yükü artar; \"onay yükü ≤ %20\" hedefi zorlaşır."),
          O("kayit", "Risk kayıt başına hesaplanır; eşik ve içerik yükseltir",
            "Geri alınabilir bir alan değişikliği toplu da olsa \"reversible\" sayılır. Kayıt sayısı eşiği aşarsa (ör. 50) ya da submit, silme veya kişisel/finansal veri varsa otomatik olarak destructive veya sensitive olur.",
            "E-postada 50 mesaja etiket eklemek serbesttir; toplu silme onay ister ve çöp kutusunda 30 gün durur.",
            "F2'ye tek karar tablosu yazılır; yolculuk, BulkEdit ve AT-14 aynı sonucu verir."),
          O("ayri", "Ayrı bir \"toplu\" sınıfı: grant verilebilir ama tavanlı",
            "Toplu işlem için özel sınıf; grant verilebilir, kayıt sayısı tavanı ve örnek önizleme zorunlu.",
            "Kurumsal kartın aylık harcama limiti.",
            "Risk sınıfı sayısı altıya çıkar; onay matrisi genişler."),
      ],
      oneri=["kayit"],
      oneri_neden="Riski kayıt sayısı değil işlemin geri alınabilirliği ve verinin türü belirler; eşik ise toplu hatanın etki alanını sınırlar.",
      kaynak=["Claude raporu A1", "Codex D02", "AI-first incelemesi 1"], etkiler=["F2", "F3", "BulkEdit", "AT-14"]),

    S("C02", "celiski", "P1", "sen",
      "Grant (önceden verilmiş sınırlı yetki) canlıya çıkışta olsun mu?",
      "AT-14 bir yayın kapısı ve \"yetki kapsamındakiler onaysız uygulanır\" diyor; yani grant canlıya çıkıştan önce çalışmalı. Plan ise grant'in ait olduğu delegated modu canlıdan üç ay sonra açıyor. Bu hâliyle AT-14 hiç geçemez.",
      [
          O("sonra", "Canlıda grant yok; her YZ değişikliği onaylanır, grant üç ay sonra",
            "İlk sürümde YZ yalnız önerir ve her değişiklik için onay alır. AT-14 ikiye bölünür: şimdi onaylı yol, sonra grant yolu. Onay çubuğundaki \"bu tür için yetki ver\" düğmesi o zamana kadar gizli kalır.",
            "Yeni çalışanın ilk aylarda her harcamayı yöneticisine onaylatması, güven oluşunca imza yetkisi alması.",
            "Güvenlik varsayımınla (YZ insan onayı olmadan yazmaz) birebir uyumlu."),
          O("sinirli", "Canlıda sınırlı grant: yalnız geri alınabilir, küçük ve kısa süreli",
            "Grant yalnız reversible sınıfında, düşük kayıt tavanıyla ve birkaç saatliğine verilebilir.",
            "Kasiyere günlük 500 TL'ye kadar iade yetkisi verilmesi.",
            "AT-14 canlı öncesi geçebilir; onay yorgunluğu azalır, risk sınırlı kalır."),
          O("tam", "Canlıda tam delegated mod",
            "Ajan kullanıcının verdiği yetki içinde serbestçe çalışır.",
            "Otomatik pilotu ilk uçuşta tam açmak.",
            "Önerilmez; kanıt olmadan en yüksek güven düzeyi verilir."),
      ],
      oneri=["sonra"],
      oneri_neden="Grant bir güven ödülüdür; önce onaylı yolda başarı ölçülür. Onay yükü çok yüksek çıkarsa \"sınırlı\" seçeneğine geçilir.",
      kaynak=["Claude raporu A2", "AI-first incelemesi 2", "Tutarlılık incelemesi 3"], etkiler=["AT-14", "F1", "F3", "K7"]),

    S("C03", "celiski", "P1", "teknik",
      "Canlı güncelleme olayları ne taşısın?",
      "B6 \"olay yalnız 'değişti' sinyali taşır; ilerleme yüzdesi de iş bilgisidir\" diyor. E4, mekanizma çizimi ve teknoloji tablosu ise olayın ilerleme yüzdesi taşıdığını söylüyor. Yetkisi iptal edilen kullanıcıyı korumanın yolu buna bağlı.",
      [
          O("sinyal", "Yalnız \"değişti\" sinyali; içerik ve ilerleme sunucudan ayrıca çekilir",
            "Olay yalnız hangi kaydın değiştiğini söyler; ilerleme yüzdesi ve durum izinli bir istekle okunur.",
            "Telefon kilit ekranında \"1 yeni mesaj\" yazması, mesajın kendisinin görünmemesi.",
            "Yetkisi iptal edilen kişi açık kalmış bağlantıdan iş bilgisi göremez; E4, çizim ve tablo düzeltilir."),
          O("yuzde", "Olay ilerleme yüzdesi ve durum taşır",
            "Frappe'nin hazır ilerleme olayı kullanılır.",
            "Kilit ekranında mesajın tamamının görünmesi.",
            "Daha basit, ama iptal sonrası bilgi sızabilir; M19 güvencesi zayıflar."),
      ],
      oneri=["sinyal"],
      oneri_neden="Güvenlik güvencesini koruyan tek seçenek; ek maliyeti saniyede en fazla bir küçük istek.",
      kaynak=["Claude raporu A3", "Tutarlılık incelemesi 1"], etkiler=["B6", "E4", "M19"]),

    S("C04", "celiski", "P1", "teknik",
      "Ant Design bileşenleri nerede doğrudan kullanılabilir?",
      "C1 \"uygulama kodu antd'yi doğrudan kullanır\" diyor. Karar bölümü \"Ant Design'ı domain katmanına kapatmak\", teknoloji tablosu ise \"yalnız @aep/ui\" diyor. İki geliştirici bu belgeyle iki farklı kod yazar.",
      [
          O("c1", "Uygulama temel bileşenleri doğrudan kullanır; iş bileşenleri @aep/ui'de; sözleşmelere antd girmez",
            "Düğme, düzen, tablo gibi genel parçalar doğrudan antd'den gelir. İş anlamı taşıyan bileşenler (öneri düzenleyici, onay çubuğu) domain katmanında sarmalanır. Katalog ve sözleşme paketlerine antd tipi girmez.",
            "Evi hazır kapı ve pencerelerle yapmak, ama elektrik tesisatını standart şemaya göre döşemek.",
            "Karar bölümü, teknoloji tablosu ve çizim açıklaması C1'e göre düzeltilir; lint kuralı yalnız sözleşme paketlerinde uygulanır."),
          O("hepsi", "Her şey sarmalanır; uygulama antd görmez",
            "Tüm bileşenler @aep/ui üzerinden gelir.",
            "Her mobilyayı özel ölçüyle yaptırmak: tutarlı ama pahalı ve yavaş.",
            "Sarmalayıcı bakımı ağırlaşır; YZ kod araçlarının antd bilgisi işe yaramaz."),
          O("serbest", "Sınır yok; her yerde antd",
            "Katalog ve sözleşmeler de antd tiplerini kullanır.",
            "Hızlı başlamak, beş yıl sonra kütüphane değişince her ekranı yeniden yazmak.",
            "Değiştirilebilirlik deneyleri (AT-02, AT-03) geçemez."),
      ],
      oneri=["c1"],
      oneri_neden="C1 zaten belgenin en ayrıntılı kuralı; hem hız hem değiştirilebilirlik sağlıyor.",
      kaynak=["Claude raporu A4", "Codex D14", "Tutarlılık incelemesi 2"], etkiler=["C1", "Karar", "Teknoloji tablosu"]),

    S("C05", "celiski", "P1", "teknik",
      "Faz sırası ve kabul bağımlılıkları nasıl düzeltilsin?",
      "Faz 01'in çıkış şartı AT-26, faz 03'te gelen grant ve Run'ı istiyor. AT-20 faz 04'teki www hesap sayfasını istiyor. İlk dilim \"YZ ChangeSet\" içeriyor ama YZ ile yazma faz 03'te. Bir faz bitmeden sonrakine geçilmiyorsa bu plan kapanamaz.",
      [
          O("onkosul", "Her gereksinim ve deneye önkoşul; erken fazda sahte (stub) sözleşme testi, tam entegrasyon sonra",
            "Erken fazda Run ve grant'in sahte sürümüyle sözleşme sınanır; gerçek entegrasyon kabulü sonraki fazda ayrı bir adım olur.",
            "Binada elektrik tesisatının önce test lambasıyla denenmesi; asıl avizelerin sonra takılması.",
            "Faz 01 kendi kapsamında kapanabilir; kabul tablosunda \"sözleşme testi\" ve \"entegrasyon kabulü\" ayrı görünür."),
          O("dilim", "Fazları kaldır; yalnız uçtan uca dikey dilimler",
            "Her dilim kendi içinde her katmanı bitirir.",
            "Evi oda oda bitirmek.",
            "Plan bölümü yeniden yazılır; faz filtresi kalkar."),
          O("kalsin", "Mevcut hâli kalsın",
            "Metin olduğu gibi kalır.",
            "Olmayan bir anahtarla kapıyı açmaya çalışmak.",
            "Önerilmez; faz 01 hiçbir zaman kapanamaz."),
      ],
      oneri=["onkosul"],
      oneri_neden="Mevcut fazları korur, yalnız bağımlılıkları görünür yapar; Codex raporunun önerdiği düzeltme de budur.",
      kaynak=["Claude raporu A5", "Codex D03", "Uygulanabilirlik incelemesi 7"], etkiler=["Plan", "AT-20", "AT-21", "AT-26", "E3"]),

    S("C06", "celiski", "P1", "sen",
      "Yayın kapısında \"çalıştırılmadı\" sonucu ne anlama gelsin?",
      "K7 \"tüm yayın kapısı deneyleri geçmiş olmalı\" diyor; K9 ise \"çalıştırılmadı (not_run) yayını durdurmaz\" diyor. Aynı sürüm birine göre yayımlanır, diğerine göre yayımlanamaz.",
      [
          O("siki", "Yalnız \"geçti\" kapıyı açar; \"uygulanmaz\" gerekçeli ve onaylı istisnadır",
            "\"Kaldı\" ve \"çalıştırılmadı\" kapıyı kapalı tutar. Ürüne uymayan kontrol gerekçesiyle \"uygulanmaz\" işaretlenir ve bir kişi onaylar.",
            "Uçağın kalkış kontrol listesinde işaretlenmemiş madde \"kalkış yok\" demektir.",
            "K9 düzeltilir; yayın karar tablosuna dört sonuç ve örnekleri eklenir."),
          O("gevsek", "\"Çalıştırılmadı\" sürüm notunda görünür ama yayını durdurmaz",
            "Mevcut K9 kuralı korunur.",
            "Araç muayenesinde bir testi atlayıp raporda \"test edilmedi\" yazmak.",
            "Güvenlik kapısı çalıştırılmadan yayın yapılabilir."),
      ],
      oneri=["siki"],
      oneri_neden="Yayın kapısının tek amacı yayını durdurabilmektir; çalıştırılmamış kapı kapı değildir.",
      kaynak=["Codex D01"], etkiler=["K7", "K9"]),

    S("C07", "celiski", "P1", "sen",
      "İlk sürümde çevrimdışı çalışma olsun mu?",
      "E3 çevrimdışı yazma kuyruğunu faz 01'e koyuyor, plan ise \"çevrimdışı senkron\"u faz 04'te anlatıyor. Karar kaydı \"çevrimdışı işlem kuyruğu\" seçmiş; önerisi \"yerel taslak + çevrimiçi gönderim\".",
      [
          O("yok", "Yok; bağlantı koparsa açık formdaki taslak korunur",
            "İnternet giderse sayfadaki taslak kaybolmaz; bağlantı gelince kullanıcı gönderir.",
            "Web e-postasında bağlantı kopunca taslağın durması; tekrar \"Gönder\"e basmak.",
            "E3 ikiye bölünür: çevrimiçi revizyon kontrolü faz 01, çevrimdışı kuyruk kapsam dışı."),
          O("okuma", "Çevrimdışı okuma ve taslak; yazma kuyruğu yok",
            "Son açılan kayıtlar internetsiz okunur, taslak yazılabilir, gönderim çevrimiçi yapılır.",
            "Belge düzenleyicilerin çevrimdışı modu.",
            "Hassas olmayan veriler cihazda sınırlı süre tutulur."),
          O("kuyruk", "Tam çevrimdışı yazma kuyruğu (faz 04)",
            "İnternet yokken yapılan değişiklikler sıraya girer, bağlantı gelince gönderilir.",
            "Saha satış uygulamasının depoda internet yokken sipariş alıp sonra senkronlaması.",
            "Kuyruk ve oturum kuralları (C09) ile çakışma inceleme ekranı zorunlu olur."),
      ],
      oneri=["yok"],
      oneri_neden="Gerçek bir saha işi yoksa çevrimdışı kuyruk en pahalı ve en riskli özelliklerden biridir. Saha işi varsa \"kuyruk\" seç.",
      kaynak=["Claude raporu A5", "Codex D03", "Karar kaydı: offline"], etkiler=["E3", "E2", "Plan"]),

    S("C08", "celiski", "P1", "sen",
      "Hassas veri içeren taslak cihazda tutulsun mu?",
      "Karar bölümü \"hassas taslak cihazda şifreli ve süreli tutulur\" diyor; E3 ise \"hassas veri sınıfı cihazda tutulmaz\".",
      [
          O("hayir", "Hayır; hassas veri cihazda hiç tutulmaz",
            "Kişisel, finansal veya permlevel korumalı alanlar tarayıcıda kalıcı saklanmaz.",
            "Bankacılık uygulamalarının hesap dökümünü telefonda saklamaması.",
            "Karar bölümündeki cümle E3'e göre düzeltilir."),
          O("sifreli", "Şifreli ve süreli tutulur",
            "Taslak cihazda şifrelenir ve belirli süre sonra silinir.",
            "Mesajlaşma uygulamalarının mesajları telefonda şifreli tutması.",
            "Anahtar yönetimi ve cihaz kaybı senaryoları eklenir."),
      ],
      oneri=["hayir"],
      oneri_neden="Tarayıcıda şifreleme anahtarını güvenle saklamak zordur; hassas taslak sunucudaki çalışma kopyasında daha güvende.",
      kaynak=["Claude raporu A6", "Tutarlılık incelemesi 8"], etkiler=["E2", "E3", "G7"]),

    S("C09", "celiski", "P1", "sen",
      "Çevrimdışı kuyruk oturum bittiğinde ne yapsın?",
      "E3 kuyruğu \"bağlantı gelince sırayla oynatır\" diyor. Çıkış, kullanıcı değişimi, hesap kapatma veya mutlak oturum bitişinden sonra kuyruğun kimin adına gönderileceği yazmıyor.",
      [
          O("bagli", "Kuyruk onu oluşturan kullanıcıya ve oturuma bağlı",
            "Çıkış, kullanıcı değişimi veya hesap kapatmada kuyruk silinir. Oynatmadan önce yeniden giriş ve güncel yetki kontrolü yapılır; onaylı YZ değişikliği revizyon değiştiyse yeniden incelemeye düşer.",
            "Ortak kasada çıkış yapan kasiyerin bekleyen işlemlerinin sonraki kasiyer adına gönderilmemesi.",
            "E3'e kuyruk-oturum kuralı ve kabul deneyi eklenir."),
          O("serbest", "Kuyruk cihazda kalır; sonraki girişte gönderilir",
            "Kim giriş yaparsa kuyruk onun oturumuyla gönderilir.",
            "Başkasının imzasıyla bekleyen evrakı işleme koymak.",
            "Önerilmez; yanlış kullanıcı adına yazma riski doğar."),
      ],
      oneri=["bagli"], goster={"soru": "C07", "iceren": "kuyruk"},
      oneri_neden="Yazma her zaman gerçek kullanıcının güncel yetkisine bağlı olmalı.",
      kaynak=["Claude raporu E"], etkiler=["E3", "M19", "M25"]),

    S("C10", "celiski", "P1", "sen",
      "Canlıya geçiş nasıl olsun?",
      "Karar kaydı \"tek seferde geçiş\" seçmiş; önerisi \"dikey dilimlerle kademeli\". Belge geliştirmeyi kademeli, canlıya geçişi tek kesim olarak yazıyor.",
      [
          O("tek", "Tek kesim: belirli bir gün herkes yeni arayüze geçer",
            "Bütün modüller hazır olunca geçiş tek seferde yapılır.",
            "Bir bankanın çekirdek sistemini bir hafta sonunda değiştirmesi.",
            "En az iki geçiş provası, Desk'e dönüş provası ve tam eşitlik matrisi zorunlu."),
          O("kademeli", "Kademeli: modül modül geçiş",
            "Hazır olan modül canlıya çıkar; diğerleri Desk'te kalır.",
            "Şirketin önce satış, sonra muhasebe ekibini yeni sisteme alması.",
            "Geri dönüş riski küçülür; iki arayüz bir süre birlikte yaşar."),
          O("paralel", "Paralel: iki arayüz aynı veride, eskisi tarihiyle kapanır",
            "Kullanıcı istediği arayüzü seçer; eski arayüzün kapanış tarihi ilan edilir.",
            "Web sitelerinin \"yeni tasarımı dene\" düğmesi.",
            "Destek yükü artar; kullanım verisi geçişi yönlendirir."),
      ],
      oneri=["kademeli"], goster={"soru": "U01", "iceren": ["canli", "pilot"]},
      oneri_neden="Karar kaydının kendi önerisi; hata olursa etkisi tek modülle sınırlı kalır.",
      kaynak=["Açık kararlar: canlıya geçiş"], etkiler=["K7", "Plan"]),

    S("C11", "celiski", "P2", "sen",
      "Takvim mi, Gantt ve kaynak planlayıcı mı?",
      "Karar kaydında bir karar yalnız takvimi, diğeri Gantt ve kaynak planlayıcıyı seçiyor.",
      [
          O("takvim", "Yalnız takvim görünümü", "Kayıtlar tarih üzerinde görünür, sürükle-bırak ile taşınır.", "Ortak takvim uygulamaları.", "L4 olduğu gibi kalır."),
          O("gantt", "Gantt ve kaynak planlayıcı da ilk sürümde", "Görev bağımlılıkları ve kaynak yükü planlanır.", "Proje yönetim yazılımlarındaki çubuk grafik.", "Yeni gereksinim grubu ve deneme (PoC) gerekir."),
          O("sonra", "Gantt sonra, gerçek ihtiyaç ve deneme ile", "Önce takvim; Gantt ihtiyacı kanıtlanınca eklenir.", "Önce kira, sonra ev almak.", "Açık kararlar satırı kapanır; Gantt ertelenmiş kapsam olur."),
      ],
      oneri=["sonra"],
      oneri_neden="Gantt pahalı bir yüzeydir; somut kullanıcı ihtiyacı görülmeden yapılmamalı.",
      kaynak=["Açık kararlar: takvim ve Gantt"], etkiler=["L4"]),

    S("C12", "celiski", "P2", "sen",
      "Yorum, atama ve bildirim akışları ne zaman yeni arayüze gelsin?",
      "Karar kaydı hem \"tam eşitlik\" hem \"ilk fazda Desk'te devam\" seçmiş; kaynağın kendisi bunu tutarsız bulmuş.",
      [
          O("desk", "İlk fazda Desk'te kalsın, yeni arayüz bağlantı versin", "Kullanıcı yorum için Desk'e gider.", "Yeni uygulamanın eski sisteme kısayol vermesi.", "Yalnız mevcut Desk kullanıcıları varsa anlamlıdır."),
          O("hepsi", "İlk sürümde hepsi yeni arayüzde", "Yorum, atama ve bildirimler baştan yeni arayüzde.", "Ekip içi mesajlaşmanın ürünün içinde olması.", "İlk sürüm büyür."),
          O("yorum", "İlk sürümde yorum ve bildirim; atama sonra", "En çok kullanılan iki akış önce gelir.", "Ekip içi mesajlaşmada önce mesaj, sonra görev atama.", "Kapsam dengeli kalır."),
      ],
      oneri=["yorum"],
      oneri_neden="Sıfırdan başlayan üründe Desk'e yönlendirmek garip olur; yorum ve bildirim de işbirliğinin çekirdeğidir.",
      kaynak=["Açık kararlar: işbirliği"], etkiler=["B8"]),

    S("C13", "celiski", "P2", "teknik",
      "YZ önerisi kabul edilene kadar nerede dursun?",
      "Yolculuk \"öneriler taslak katmanında durur\" diyor; E9 \"doğrudan taslağa değil, öneri katmanına yazılır\" diyor.",
      [
          O("oneri", "Ayrı öneri katmanı; kullanıcı kabul edince taslağa geçer",
            "Öneri, kullanıcının kendi yazdığıyla karışmaz.",
            "Metin düzenleyicide \"değişiklikleri izle\": önerilen değişiklik kabul edilene kadar metne karışmaz.",
            "Yolculuk metni E9'a göre düzeltilir."),
          O("taslak", "Doğrudan taslağa yazılır",
            "Öneri taslak alanına yazılır; kullanıcı düzeltir.",
            "Başkasının defterine doğrudan yazmak.",
            "Kullanıcının kendi yazdığıyla YZ önerisi ayırt edilemez."),
      ],
      oneri=["oneri"],
      oneri_neden="Kullanıcının düzenlediği alanın YZ tarafından ezilmemesi kuralını (E9) ancak ayrı katman korur.",
      kaynak=["Tutarlılık incelemesi 17"], etkiler=["E9", "Varsayılan yolculuk"]),

    # ------------------------------------------------------------------ YZ ÖNCELİKLİ DENEYİM
    S("Y01", "yz", "P1", "sen",
      "YZ modelleri nerede çalışsın?",
      "Belge \"hassas veri yerel veya özel modelde, diğerleri yönetilen API'de\" diyor ama sağlayıcı, model ve maliyet tanımlı değil. Bu, ilk dilimi bloklayan bir boşluk.",
      [
          O("api", "Yönetilen model API'si; kişisel veri modele maskelenerek gider",
            "Bulut model sağlayıcısı kullanılır; kişisel veri maskelenir, veri sınıfı tablosu uygulanır.",
            "Şirketlerin kurumsal YZ hizmetlerini müşteri adlarını gizleyerek kullanması.",
            "Tek kalite düzeyi ve tek değerlendirme; teknoloji tablosuna sağlayıcı satırı eklenir."),
          O("karma", "Göreve göre yönlendirme: hassas veri kendi sunucumuzda, diğerleri API'de",
            "Hassas veri kendi sunucumuzdaki açık kaynak modelde işlenir.",
            "Hastanenin hasta verisini kendi sunucusunda işlemesi.",
            "GPU sunucusu, iki kalite düzeyi ve iki ayrı değerlendirme seti gerekir (karar kaydının seçimi)."),
          O("yerel", "Yalnız kendi sunucumuzda açık model",
            "Hiçbir veri dışarı çıkmaz.",
            "Savunma sanayinde internetten yalıtılmış sistemler.",
            "Yüksek donanım maliyeti; kalite riski."),
      ],
      oneri=["api"],
      oneri_neden="Tek kişilik veya küçük ekipte en düşük işletim yükü. Hassas veri zaten veri sınıfı tablosuyla sınırlanıyor.",
      kaynak=["Uygulanabilirlik incelemesi 6", "AI-first incelemesi 7", "Karar kaydı: model-host"], etkiler=["G4", "Teknoloji tablosu", "M23"]),

    S("Y02", "yz", "P1", "sen",
      "Kişisel veri YZ modeline yurt dışında işlenebilir mi (KVKK)?",
      "Veri yerleşimi karar kaydında \"keşif gerekiyor\" durumunda. Hetzner'ın Türkiye lokasyonu yok; model sağlayıcılarının çoğu ABD veya AB'de.",
      [
          O("hukuk", "Hukukçu görüşüne kadar kişisel veri içeren hiçbir istem dışarı gitmez",
            "Maskeli veya anonim veri modele gidebilir; kişisel veri gidemez.",
            "Sözleşme imzalanmadan müşteri listesini dış firmaya vermemek.",
            "Pilot üretim verisiyle değil, maskeli kopyayla yapılır."),
          O("riza", "Açık rıza ve veri işleme sözleşmesiyle yurt dışı işleme",
            "Kullanıcıdan açık rıza alınır, sağlayıcıyla sözleşme yapılır.",
            "Bulut e-posta hizmetlerinin KVKK aydınlatma metinleri.",
            "Rıza Kaydı'na YZ işleme rızası eklenir; hukuki metin gerekir."),
          O("bolge", "Yalnız Türkiye veya AB'de barındırılan model",
            "Sağlayıcı seçimi bölgeyle sınırlanır.",
            "Kamu kurumlarının yurt içi bulut şartı.",
            "Model seçeneği daralır; maliyet artabilir."),
      ],
      oneri=["hukuk"],
      oneri_neden="Geri alınamaz bir hukuki riski teknik kararla almamak gerekir. Maskeleme ile ürün yine çalışır.",
      kaynak=["Açık kararlar: veri yerleşimi", "Uygulanabilirlik incelemesi 6"], etkiler=["G4", "M23", "Dilim kabulü"]),

    S("Y03", "yz", "P1", "sen",
      "İlk sürümde hangi YZ yüzeyleri olsun?",
      "Belge beş YZ yüzeyi tanımlıyor ama yalnız birinin (toplu seçimle öznitelik tamamlama) kabul deneyi var. Her yüzey kendi başarı ölçütünü ister.",
      [
          O("komut", "Komut paleti ve asistan",
            "Kullanıcı ne yapmak istediğini yazar, sistem ilgili ekranı ve eylemi getirir.",
            "Bilgisayarda arama çubuğuna yazıp programı açmak.",
            "Niyet girişi (I10) ilk sürümde yer alır."),
          O("form", "Alan ve form yardımı",
            "Formda alan doldurma, açıklama ve öneri.",
            "E-postada cümlenin devamını önermesi.",
            "Öneri düzenleyici ve dayanak gösterimi ilk sürümde yer alır."),
          O("toplu", "Satır ve toplu seçim eylemleri",
            "Seçili kayıtlar üzerinde toplu öneri ve değişiklik.",
            "Tablo programında seçili hücrelere tek seferde işlem yapmak.",
            "Varsayılan yolculuğun kalbi; AT-13 ve AT-14 bunu ölçer."),
          O("rapor", "Rapor ve pano üretimi (doğal dilden rapor)",
            "Kullanıcı sorusunu yazar, sistem raporu kurar.",
            "Tablo programında \"bu verileri özetle\" demek.",
            "Filtre doğruluğu için ayrı değerlendirme seti ve onay adımı (Y04) gerekir."),
          O("akis", "Workflow, hata ve denetim yardımı",
            "Hata veya onay adımında sonraki adımı önerir.",
            "Navigasyonun \"yol kapalı, şu yoldan git\" demesi.",
            "Sonraki adım kartı ilk sürümde yer alır."),
      ],
      tip="cok", oneri=["komut", "form", "toplu"],
      oneri_neden="İlk sürümde değeri ölçülebilen üç yüzey. Rapor üretimi filtre doğruluğu testi hazır olunca, akış yardımı ise workflow'lar netleşince eklenmeli.",
      kaynak=["AI-first incelemesi 4", "Karar kaydı: ai-surfaces"], etkiler=["I1", "Plan", "Kabul deneyleri"]),

    S("Y04", "yz", "P1", "sen",
      "Doğal dilden rapor çalışmadan önce kullanıcıya gösterilsin mi?",
      "Filtre yanlış kurulursa sorgu deterministik olsa bile rakamlar yanlış olur. Belge bunun için bir onay adımı tanımlamıyor.",
      [
          O("onay", "Evet; \"şöyle anladım\" filtre çipleri gösterilir, kullanıcı onaylar",
            "Rapor çalışmadan önce sistemin anladığı filtreler görünür; kullanıcı düzeltir veya onaylar.",
            "Uçak bileti alırken \"İstanbul → Berlin, 12 Ekim, 1 yetişkin\" özetini görüp onaylamak.",
            "D1 ve I2'ye onay adımı, K2'ye filtre doğruluğu ölçütü eklenir."),
          O("dogrudan", "Hayır; rapor hemen çalışır, filtre sonra düzenlenir",
            "Hız öne çıkar, düzeltme sonuçtan sonra yapılır.",
            "Arama motorunda sonuçları görüp sorguyu değiştirmek.",
            "Yanlış rakamla karar verme riski artar."),
      ],
      oneri=["onay"], goster={"soru": "Y03", "iceren": "rapor"},
      oneri_neden="Rapordan karar çıkar; yanlış anlaşılan bir filtre fark edilmeden yanlış karara yol açar.",
      kaynak=["AI-first incelemesi 4"], etkiler=["D1", "I2", "K2"]),

    S("Y05", "yz", "P1", "teknik",
      "YZ'nin \"güven\" etiketi neye dayansın?",
      "I4 \"Yüksek, Orta, Düşük\" kategorisi kullanıyor, ama kategorinin nasıl hesaplandığı yazılmıyor. Modelin kendi \"eminim\" beyanının yüksek güven diye gösterilmesini engelleyen bir kural yok.",
      [
          O("olcum", "Yalnız ölçülmüş sinyalden; kalibrasyon bitene kadar etiket yok",
            "Güven, kaynakta birebir eşleşme, çapraz doğrulama ve değerlendirme setindeki başarıdan hesaplanır. Kalibrasyon yapılana kadar yalnız dayanak gösterilir.",
            "Hava durumunun \"%70 yağmur\" diyebilmesi, çünkü geçmiş tahminlerle ölçülmüştür.",
            "I4'e hesaplama kuralı, K2'ye kalibrasyon ölçütü eklenir; \"Orta\" güven grant ile otomatik uygulanmaz."),
          O("model", "Modelin kendi beyanı gösterilir",
            "Model \"yüksek güven\" derse öyle görünür.",
            "Stajyerin \"bence doğru\" demesi.",
            "Kullanıcı yanlış güvene yönlendirilebilir."),
          O("yok", "Hiç güven etiketi yok, yalnız dayanak",
            "Her öneri kaynağıyla gösterilir, derece verilmez.",
            "Ansiklopedi maddesinin yalnız kaynak göstermesi.",
            "En basit yol; ancak düşük güvenli öneriyi ayırmak zorlaşır."),
      ],
      oneri=["olcum"],
      oneri_neden="Kalibre edilmemiş güven, güven etiketi olmamasından daha zararlıdır.",
      kaynak=["AI-first incelemesi 9", "Codex D09"], etkiler=["I4", "K2", "F3"]),

    S("Y06", "yz", "P2", "sen",
      "İki netleştirme sorusundan sonra belirsizlik sürerse ne olsun?",
      "Yolculuk en fazla iki netleştirme sorusuna izin veriyor, ama sonrasında ne olacağını söylemiyor.",
      [
          O("ayir", "Belirsiz kayıtlar ayrılır ve manuel kuyruğa gider; kalanlarla devam edilir",
            "YZ emin olamadığı kayıtları \"belirsiz\" diye işaretler ve dokunmaz; kullanıcı onları elle tamamlar.",
            "Kargo şirketinin adresi okunamayan paketleri ayırıp diğerlerini dağıtması.",
            "Yolculuğa ve toplu sonuç ekranına \"belirsiz\" durumu eklenir."),
          O("dur", "Bütün iş durur; kullanıcı klasik yola geçer",
            "Belirsizlik tüm işi keser.",
            "Tek bir okunamayan paket yüzünden bütün dağıtımın durması.",
            "Güvenli ama verimsiz."),
          O("sor", "Soru sınırı kaldırılır",
            "YZ gerektiği kadar soru sorar.",
            "Her adımda onay isteyen form sihirbazı.",
            "Kullanıcı yorulur; sohbet uzar."),
      ],
      oneri=["ayir"],
      oneri_neden="Kesin olanı ilerletir, belirsiz olanı insana bırakır; verim ve güvenlik birlikte korunur.",
      kaynak=["AI-first incelemesi 9", "Codex D09"], etkiler=["Varsayılan yolculuk", "I4"]),

    S("Y07", "yz", "P2", "sen",
      "YZ kullanıcı istemeden öneri gösterebilsin mi?",
      "I10 başlangıç ekranında \"bağlamlı öneriler\" diyor, ama ne zaman, ne sıklıkta ve kimin kotasıyla gösterileceği tanımlı değil.",
      [
          O("yok", "İlk sürümde hayır; YZ yalnız istenince çalışır",
            "Kullanıcı sormadıkça YZ bir şey önermez.",
            "Sesli asistanın yalnız çağırınca konuşması.",
            "Maliyet ve rahatsızlık riski sıfırlanır; AI-first etkisi azalır."),
          O("sinirli", "Sınırlı: başlangıç ekranında en fazla 3 öneri, modal değil, yazma başlatmaz",
            "Öneriler sayfanın kenarında durur; kapatılan öneri hatırlanır; öneri hiçbir zaman kendiliğinden değişiklik yapmaz.",
            "E-postanın \"bu mesaja cevap vermedin\" hatırlatması.",
            "I grubuna proaktif öneri satırı eklenir: tetikleyici, sıklık sınırı, kota."),
          O("serbest", "Serbest: her ekranda öneri",
            "YZ gördüğü her fırsatta öneri sunar.",
            "Eski ofis programlarının sürekli araya giren yardımcı karakteri.",
            "Rahatsızlık ve maliyet riski yüksek."),
      ],
      oneri=["sinirli"],
      oneri_neden="AI-first deneyim için yararlı, ama kural koyulmadan açılırsa kullanıcıyı yorar.",
      kaynak=["AI-first incelemesi 11"], etkiler=["I10", "I6", "E7"]),

    S("Y08", "yz", "P2", "sen",
      "YZ kullanıcı düzeltmelerinden öğrensin mi?",
      "I7 \"geri bildirim sonrası somut etki bildirilir\" diyor ama etkinin ne olduğu yazılmıyor. Düzeltmelerin değerlendirme setine dönüşü de tanımsız.",
      [
          O("set", "Düzeltmeler maskelenip insan onayıyla değerlendirme setine aday olur",
            "Model davranışı yalnız sürümlü, test edilmiş değişiklikle değişir.",
            "Çağrı merkezinde yanlış cevaplanan soruların eğitim materyaline eklenmesi.",
            "Güvenli; iyileşme sürüm sürüm gelir."),
          O("hafiza", "Şirket bazlı düzeltme hafızası; bir sonraki öneride kullanılır",
            "Şirketin tercihleri hatırlanır.",
            "Klavyenin sık yazdığın kelimeleri öğrenmesi.",
            "Hızlı iyileşme; hafıza silme ve izolasyon kuralları gerekir."),
          O("yok", "Öğrenme yok",
            "Düzeltmeler yalnız o işi etkiler.",
            "Her gün aynı hatayı yapan ama öğrenmeyen asistan.",
            "En basit; I7 metni sadeleşir."),
      ],
      oneri=["set"],
      oneri_neden="Önce kontrollü öğrenme; şirket hafızası izolasyon testleri hazır olunca eklenebilir.",
      kaynak=["AI-first incelemesi 8"], etkiler=["I7", "K2", "G7"]),

    S("Y09", "yz", "P2", "sen",
      "YZ konuşma geçmişi ne kadar saklansın?",
      "I8 \"sohbet geçmişi aranabilir ve silinebilir\" diyor ama saklama süresi yok. Saklama süresi KVKK ve maliyetle doğrudan ilgili.",
      [
          O("30", "30 gün, sonra otomatik silinir", "Kısa süreli bağlam.", "Kurumsal sohbet araçlarında sık görülen kısa saklama politikası.", "Bağlam önbelleği ve özetler de 30 günde silinir."),
          O("90", "90 gün", "Çeyreklik iş döngüsü.", "Destek taleplerinin üç ay saklanması.", "Saklama ve silme politikası buna göre yazılır."),
          O("sil", "Kullanıcı silene kadar", "Süresiz, kullanıcı kontrolünde.", "Kişisel not uygulamaları.", "KVKK açısından en zayıf seçenek."),
          O("oturum", "Yalnız oturum boyunca", "Oturum kapanınca silinir.", "Gizli sekmede gezinme.", "Çok turlu çalışma ve sonraki gün devam zorlaşır."),
      ],
      oneri=["30"],
      oneri_neden="Yarım kalan işe dönmeye yeter, gereksiz veri birikmez.",
      kaynak=["AI-first incelemesi 10", "Codex D07"], etkiler=["I8", "I9", "G7"]),

    S("Y10", "yz", "P1", "sen",
      "YZ maliyet tavanı nasıl belirlensin?",
      "AT-13 ve dilim kabulü \"işlem başına maliyet bütçe içinde\" diyor, ama bütçenin rakamı hiçbir yerde yok. Rakam olmadan bu kapı geçti mi kaldı mı söylenemez.",
      [
          O("olc", "Önce iki hafta ölç, sonra tavan koy",
            "Pilotta görev başı ve şirket başı harcama raporlanır. Tavan bu veriyle konur; o zamana kadar yumuşak tavan yalnız uyarı üretir.",
            "Yeni bir mobil hattın ilk ay faturasına bakıp paket seçmek.",
            "Sayısal parametreler tablosuna \"ölçüm sonrası\" değeri ve tarihi yazılır."),
          O("gorev", "Baştan görev başı sabit tavan",
            "Her görevin azami maliyeti baştan yazılır.",
            "Taksi ücretinin baştan sabitlenmesi.",
            "Rakam tahmine dayanır; gerçek kullanıma uymayabilir."),
          O("aylik", "Şirket başı aylık bütçe (abonelik paketine göre)",
            "Her müşterinin aylık YZ hakkı paketine göre belirlenir.",
            "Mobil operatörün aylık internet kotası.",
            "Kota aşımında ne olacağı (durdur, yavaşlat, ücretlendir) ayrıca yazılır."),
      ],
      oneri=["olc"],
      oneri_neden="Ölçmeden konan tavan ya işi gereksiz durdurur ya da hiç işe yaramaz. Uzun vadede \"aylık\" modele geçilebilir.",
      kaynak=["Claude raporu C3", "AI-first incelemesi 7"], etkiler=["E7", "K6", "AT-13"]),

    S("Y11", "yz", "P1", "sen",
      "YZ'nin başarısı nasıl ölçülsün?",
      "AT-13 \"%30 daha hızlı, ≤2 düzeltme, onay yükü ≤%20\" istiyor. Bu eşikler bir ölçüme dayanmıyor, sıralama etkisi dengelenmiyor ve 15 kişilik çalışma genel verim kanıtı gibi kullanılıyor.",
      [
          O("baseline", "Önce klasik yolun ölçümü; eşikler oradan türetilir",
            "Faz 00'da klasik yol ölçülür. Katılımcıların yarısı önce klasik, yarısı önce YZ yolunu dener. 15 kişilik çalışma keşif sayılır; canlı metrikler ayrıca izlenir.",
            "Yeni bir ilacın plaseboyla, sırası karıştırılmış gruplarda denenmesi.",
            "AT-13 yeniden yazılır; düzeltme sayısı \"100 öneride düzeltme\" oranına çevrilir."),
          O("sabit", "Mevcut sabit eşikler kalsın",
            "%30, ≤2 ve ≤%20 olduğu gibi kullanılır.",
            "Hedefi ölçmeden koymak.",
            "Hızlı ama kanıtı zayıf."),
          O("canli", "Yalnız canlı kullanım metrikleri",
            "Laboratuvar çalışması yapılmaz; canlıda kabul ve geri alma oranları izlenir.",
            "Ürünü çıkarıp kullanım verisine bakmak.",
            "Canlı öncesi kanıt olmaz."),
      ],
      oneri=["baseline"],
      oneri_neden="Hem Codex hem Claude raporu aynı zayıflığı buldu; ölçülmüş bir karşılaştırma olmadan \"%30\" bir hedef değil tahmindir.",
      kaynak=["Codex D10", "AI-first incelemesi 6", "Claude raporu C3"], etkiler=["AT-13", "Plan"]),

    S("Y12", "yz", "P2", "teknik",
      "YZ değerlendirme seti ne kadar büyük olsun?",
      "K2 yetenek başına 10–20 örnek istiyor. 20 örnekte %95 eşiği en fazla bir hata demek; model her seferinde farklı cevap verebildiği için bu ölçüm dalgalanır.",
      [
          O("20", "Yetenek başına 10–20 örnek (mevcut)", "Az ama hızlı.", "Tek soruluk sınav.", "Ölçüm dalgalı kalır."),
          O("50", "En az 50 örnek, her örnek birkaç kez çalıştırılır", "Rastgelelik tekrarla dengelenir; her setin bir sahibi olur.", "Bir öğrencinin tek sınav yerine dönem boyunca ölçülmesi.", "K2'ye tekrar sayısı ve geçme kuralı eklenir."),
          O("100", "100'den fazla ve insan etiketli", "En güçlü kanıt, en pahalı.", "Klinik araştırma.", "Etiketleme maliyeti ve süresi artar."),
      ],
      oneri=["50"],
      oneri_neden="Maliyeti makul tutarken ölçümü güvenilir yapan en küçük adım.",
      kaynak=["AI-first incelemesi 8", "Codex D10"], etkiler=["K2", "K6"]),

    S("Y13", "yz", "P2", "teknik",
      "Canlı YZ metrikleri tanımlansın mı?",
      "K3'teki günlük ölçütler yalnız teknik (şema uyumu, gecikme). Kullanıcının YZ önerisini kabul etme, düzeltme, geri alma veya klasik yola dönme oranı yok.",
      [
          O("evet", "Evet; kabul, düzenleme, geri alma, klasiğe dönüş ve bırakma oranları eşik alarmlarıyla",
            "Denetim kayıtlarından hesaplanır; eşik aşılınca uyarı gelir.",
            "Mağazanın satış yanında iade oranını da izlemesi.",
            "K3'e ürün metrikleri tablosu eklenir."),
          O("hayir", "Hayır; teknik metrikler yeterli",
            "Mevcut hâl.",
            "Yalnız kasanın çalışıp çalışmadığına bakmak.",
            "YZ'nin gerçekten işe yarayıp yaramadığı görünmez."),
      ],
      oneri=["evet"],
      oneri_neden="AI-first iddiasını canlıda doğrulayan tek veri bu.",
      kaynak=["Claude raporu C4", "AI-first incelemesi 8"], etkiler=["K3", "G5"]),

    S("Y14", "yz", "P2", "teknik",
      "YZ'nin ürettiği ekranların erişilebilirliği nasıl güvenceye alınsın?",
      "\"YZ önerisi\" ile \"kaydedilmiş değer\" ayrımı yalnız görsel; ekran okuyucu bu farkı duymaz. Otomatik erişilebilirlik taraması yalnız bileşen örneklerinde koşuyor, YZ'nin ürettiği ekranlarda koşmuyor.",
      [
          O("tam", "YZ etiketi erişilebilir adda; üretilen her örnek ekranda tarama; başlık seviyelerini sistem atar",
            "Ekran okuyucu \"YZ önerisi\" diye duyurur. Her değerlendirme örneğinin çizilmiş hâli taranır. Başlık düzenini model değil çizici belirler.",
            "Ekran okuyucu kullanan çalışanın hangi değerin önerildiğini duyabilmesi.",
            "I3, K2 ve K4'e kural eklenir."),
          O("mevcut", "Mevcut hâl yeterli",
            "Yalnız bileşen örnekleri taranır.",
            "Parçaları test edip bitmiş binayı test etmemek.",
            "Erişilebilirlik açığı YZ ekranlarında kalabilir."),
      ],
      oneri=["tam"],
      oneri_neden="WCAG 2.2 AA hedefi YZ ekranlarını da kapsar; onay ekranı ürünün en kritik ekranıdır.",
      kaynak=["AI-first incelemesi 12", "Claude raporu D6"], etkiler=["I3", "K2", "K4", "J3"]),
]
