"""Karar kitabı soru bankası, bölüm 6-9: kalite ve yayın, ekip ve belge düzeni, karar kaydı, teknik varsayılanlar."""
from ortak import S, O

SORULAR = [
    # ------------------------------------------------------------------ TEST, ÖLÇÜM VE YAYIN
    S("T01", "kalite", "P1", "sen",
      "Her zorunlu (MUST) gereksinim en az bir teste bağlansın mı?",
      "132 gereksinimden yalnız 21'i bir kabul deneyine bağlı; 93'ünde ne deney ne kabul ifadesi var. Yedi değişmez kuraldan biri olan \"kill switch 30 saniyede kapatır\" hiçbir deneyde yok.",
      [
          O("hepsi", "Evet; bağlantısız MUST varsa derleme kırılır, gereksinim × test tablosu üretilir",
            "Her MUST satırı bir kabul deneyine veya otomatik teste bağlanır.",
            "Uçak bakım listesinde her maddenin karşısında bir imza olması.",
            "Gereksinim tablosuna test sütunu, derlemeye kapsama kontrolü eklenir."),
          O("p1", "Yalnız öncelikli ve güvenlik maddeleri",
            "Kritik maddeler teste bağlanır, diğerleri sonra.",
            "Önce yangın çıkışlarını denetlemek.",
            "Kapsama kısmi kalır."),
          O("hayir", "Hayır; mevcut hâl",
            "Deneyler bağımsız kalır.",
            "Test edilmemiş kuralın kâğıt üzerinde kalması.",
            "\"Tamamlandı\" demenin ölçütü olmaz."),
      ],
      oneri=["hepsi"], oneri_neden="Test edilemeyen gereksinim, gereksinim değil dilektir.",
      kaynak=["Claude raporu C1", "Uygulanabilirlik incelemesi 11", "Tutarlılık incelemesi 14"], etkiler=["Gereksinim tablosu", "build.py", "E7"]),

    S("T02", "kalite", "P1", "sen",
      "Test stratejisi geliştirmeden önce yazılsın mı?",
      "Belgede kabul deneyleri var ama test piramidi, ortamlar, örnek veri (seed), sabit cevap veren model taklidi ve deney şablonu yok. Senin kuralın \"önce testler\".",
      [
          O("once", "Evet; test stratejisi bölümü ilk iş olarak yazılır",
            "Katmanlar: birim (Vitest, Frappe ve pytest), sözleşme (şema örnekleri), bileşen (Storybook), uçtan uca (Playwright). Ortamlar: yerel Colima, CI, staging. Ayrıca örnek veri tanımı, sabit cevap veren model taklidi ve her deney için şablon (ön koşul, adımlar, otomatik mi elle mi, sahip).",
            "Mutfağa girmeden önce tadım listesini hazırlamak.",
            "Belgeye \"Test stratejisi\" bölümü eklenir; her AT şablona çevrilir."),
          O("sonra", "Geliştirme sırasında",
            "Testler kodla birlikte yazılır.",
            "Yemeği yaparken tadımı planlamak.",
            "Deneylerin nasıl koşulacağı belirsiz kalır."),
      ],
      oneri=["once"], oneri_neden="Senin çalışma kuralın ve YZ ile kod yazarken en güçlü güvence.",
      kaynak=["Claude raporu C2", "Uygulanabilirlik incelemesi 10"], etkiler=["Kabul deneyleri", "K1", "K9"]),

    S("T03", "kalite", "P1", "sen",
      "Gereksinimler nasıl önceliklendirilsin?",
      "132 gereksinimin 128'i MUST, hiçbiri MAY. \"Zorunlu\" ile \"ilk sürümde yapılacak\" aynı şey sayılıyor; önceliklendirme görünmüyor.",
      [
          O("mvp", "MUST kalıcı kalite kuralı kalır; ayrıca \"ilk sürüm\" etiketi eklenir",
            "Kural ile takvim ayrılır: MUST \"yapılırsa böyle yapılır\", ilk sürüm etiketi \"şimdi yapılır\" demektir.",
            "Yapı yönetmeliği her binada geçerlidir; hangi katın önce yapılacağı ayrı plandır.",
            "Gereksinim tablosuna \"ilk sürüm\" filtresi eklenir."),
          O("moscow", "MoSCoW: bu sürümde Must, Should, Could, Won't",
            "Her madde bu sürüm için dört gruptan birine girer.",
            "Taşınırken eşyaları \"hemen, sonra, belki, atılacak\" diye ayırmak.",
            "Seviye şeması baştan değişir."),
          O("mevcut", "Mevcut hâl",
            "Seviyeler olduğu gibi kalır.",
            "Her şeyin acil olduğu bir yapılacaklar listesi.",
            "Önceliklendirme yapılmaz."),
      ],
      oneri=["mvp"], oneri_neden="Mevcut seviyeleri bozmadan \"şimdi ne yapılacak\" sorusunu cevaplar.",
      kaynak=["Claude raporu (MUST enflasyonu)", "Codex D13", "Tutarlılık incelemesi 11"], etkiler=["Gereksinim tablosu", "Plan"]),

    S("T04", "kalite", "P2", "teknik",
      "Performans hedefleri hangi koşulda ölçülsün?",
      "K3 250 KB başlangıç JS, p75 Web Vitals ve p95 10 saniye hedefi veriyor. Ama hangi cihaz, ağ, önbellek durumu ve görev için ölçüleceği yazmıyor.",
      [
          O("profil", "Orta segment Android ve 4G profili; önbellek boş ve dolu ayrı; görev sınıfına göre ayrı hedef",
            "Kısa etkileşim, uzun iş ve büyük dosya için ayrı ölçü; 250 KB ilk girişte ölçülür; 10 saniye \"ilk kullanılabilir sonuç\" demektir.",
            "Araba yakıt tüketiminin şehir içi ve şehir dışı için ayrı verilmesi.",
            "K3'e ölçüm tablosu eklenir: metrik, başlangıç ve bitiş olayı, cihaz ve ağ, pencere."),
          O("mevcut", "Mevcut tek hedef",
            "Koşullar belirsiz kalır.",
            "\"Araba az yakar\" demek.",
            "Aynı hedef iki ekipte farklı ölçülür."),
      ],
      oneri=["profil"], oneri_neden="Ölçüm koşulu yazılmayan hedef tartışma üretir.",
      kaynak=["Codex D11"], etkiler=["K3", "I5"]),

    S("T05", "kalite", "P2", "teknik",
      "Cihaz testleri nasıl ve ne sıklıkta yapılsın?",
      "Mobil gereksinimler var, ama hangi testin her değişiklikte, hangisinin sürümde ve gerçek cihazda koşacağı tek bir kabul kaydına bağlanmamış.",
      [
          O("katman", "Her PR'da emülasyonla üç genişlik; her sürümde gerçek iPhone (Safari) ve Android (Chrome); kanıt kaydı",
            "Hızlı kontrol her değişiklikte, pahalı kontrol sürümde yapılır; ekran görüntüsü ve ağ kaydı saklanır.",
            "Araç üretiminde her parçanın ölçülmesi, test sürüşünün ise partide bir yapılması.",
            "K4 ve D10'a test aşaması sütunu eklenir."),
          O("her", "Her PR'da gerçek cihaz",
            "Her değişiklik gerçek cihazda test edilir.",
            "Her parçada test sürüşü yapmak.",
            "Çok pahalı ve yavaş."),
      ],
      oneri=["katman"], oneri_neden="Güvence ile maliyeti dengeler.",
      kaynak=["Codex D12"], etkiler=["K4", "D10", "K9"]),

    S("T06", "kalite", "P1", "sen",
      "\"YZ'yi 30 saniyede kapat\" (kill switch) için kabul deneyi eklensin mi?",
      "Kill switch belgenin yedi değişmez kuralından biri, ama hiçbir deneyde sınanmıyor.",
      [
          O("evet", "Evet; yayın kapısı olarak",
            "Kapatma düğmesine basıldığında 30 saniye içinde YZ yüzeylerinin kapandığı ve klasik ekranın çalıştığı test edilir.",
            "Yangın alarmının düzenli tatbikatla denenmesi.",
            "Yeni bir AT eklenir; E7'ye bağlanır."),
          O("hayir", "Hayır",
            "Kural yazılı kalır, sınanmaz.",
            "Acil çıkış kapısını hiç açıp denememek.",
            "Kriz anında çalışacağı bilinmez."),
      ],
      oneri=["evet"], oneri_neden="Kriz anı için yazılmış bir kural sınanmadıkça güvence değildir.",
      kaynak=["Claude raporu C1", "Uygulanabilirlik incelemesi 11"], etkiler=["E7", "Kabul deneyleri"]),

    S("T07", "kalite", "P2", "sen",
      "Kullanıcı araştırmasına kimler katılsın?",
      "AT-13 için 3 persona × 5 kullanıcının gerçek cihazda test yapması gerekiyor, ama katılımcıların nereden bulunacağı yazmıyor.",
      [
          O("musteri", "Pilot müşterilerden 5–8 gerçek kullanıcı", "İşi gerçekten yapan kişiler.", "Restoranın yeni menüyü düzenli müşterilerine tattırması.", "Pilot müşteriyle katılım anlaşması gerekir."),
          O("platform", "Uzaktan kullanıcı araştırma platformu", "Profile uygun ücretli katılımcılar.", "Anket firmasından katılımcı bulmak.", "Alan bilgisi zayıf olabilir."),
          O("ekip", "Ekip içinden", "Çalışanlar dener.", "Aşçının kendi yemeğini tatması.", "Taraflı sonuç; önerilmez."),
      ],
      oneri=["musteri"], oneri_neden="YZ'nin değeri ancak işi bilen kişide ölçülür.",
      kaynak=["Uygulanabilirlik incelemesi 10", "Codex D10"], etkiler=["AT-13"]),

    S("T08", "kalite", "P1", "teknik",
      "Belgenin kendi kontrol betikleri güçlendirilsin mi?",
      "Codex, bir gereksinimin fazı silindiğinde doğrulama betiğinin bunu yakalamadığını kanıtladı (D15). Anlamca yanlış göndermeler (ör. \"kabul deneyi E3\") ve bilinen çelişki cümleleri de betiklere takılmıyor.",
      [
          O("guclu", "Evet; her gereksinim geçerli faz taşısın, çelişki cümleleri yasak listede olsun, göndermeler hedefine göre denetlensin",
            "Faz kontrolü bozuk bir kopyayla sınanır (bozuk kopya kırmızı, gerçek belge yeşil olmalı). Kapanan bulgular regresyon listesine girer.",
            "Kasadaki sayım makinesinin sahte parayla düzenli denenmesi.",
            "validate.py ve check.js güncellenir; belge QA'sı kendi hatasını da yakalar."),
          O("mevcut", "Mevcut betikler yeterli",
            "Yalnız biçim kontrolü.",
            "Sayım makinesini hiç denememek.",
            "Aynı hatalar geri gelebilir."),
      ],
      oneri=["guclu"], oneri_neden="Belge her turda büyüyor; tutarlılığı insan gözüne bırakmak artık yetmiyor.",
      kaynak=["Codex D15", "Tutarlılık incelemesi 9"], etkiler=["validate.py", "check.js"]),

    # ------------------------------------------------------------------ EKİP, SAHİPLİK, BELGE DÜZENİ
    S("E01", "ekip", "P1", "sen",
      "Projeyi kim geliştirecek?",
      "Karar kaydı \"platform ekibi\" seçmiş, ama belgede ekip, rol ve iş yükü tanımı yok. Frappe tarafındaki iş (yürütücü, Run, risk politikası, YZ servisi, kimlik köprüsü, OTP) çok büyük.",
      [
          O("solo", "Ben ve YZ kodlama ajanları; faz kapılarında dış uzman",
            "Kodu Claude Code ve Codex yazar, ben yönetir ve onaylarım; güvenlik ve Frappe için dönemsel dış uzman.",
            "Tek kişilik stüdyonun serbest çalışan uzmanlarla çalışması.",
            "Kapsam küçültülür; her faz kapısında dış inceleme bütçesi ayrılır."),
          O("kucuk", "Ben, 1–2 geliştirici ve YZ ajanları",
            "Günlük kod incelemesi içeride yapılır.",
            "Küçük bir yazılım atölyesi.",
            "RACI tablosu küçük ekibe göre yazılır."),
          O("dis", "Dış ekip (ajans veya Frappe iş ortağı)",
            "Geliştirme dışarıda, ürün kararları bende.",
            "Evi müteahhide yaptırmak.",
            "Sözleşme, kabul ve teslim kuralları bu belgeye dayanır."),
          O("platform", "Ayrı frontend, Frappe ve işletim ekipleri (karar kaydının seçimi)",
            "Tam bir platform organizasyonu.",
            "Kendi mühendislik departmanı olan şirket.",
            "Belgenin mevcut ölçeği bu modele göre."),
      ],
      oneri=None, oneri_neden="Bu senin durumun; cevaba göre belgenin kapsamı ve sıralaması yeniden ayarlanır.",
      kaynak=["Claude raporu B9", "Uygulanabilirlik incelemesi 9", "Karar kaydı: team"], etkiler=["Plan", "RACI", "K12"]),

    S("E02", "ekip", "P1", "sen",
      "Frappe tarafındaki (custom app) işi kim yapacak?",
      "Yürütücü, Run, risk politikası ve kimlik köprüsü güvenlik açısından kritik ve Frappe deneyimi ister.",
      [
          O("yzuzman", "YZ ajanları yazar, Frappe deneyimli serbest geliştirici inceler",
            "Hızlı üretim, uzman gözü.",
            "Taslağı stajyerin yazıp kıdemli ustanın kontrol etmesi.",
            "İnceleme bütçesi ve takvimi plana girer."),
          O("ortak", "Frappe iş ortağı firma",
            "Frappe'yi en iyi bilen dış firma geliştirir.",
            "Aracı yetkili serviste yaptırmak.",
            "Maliyet yüksek, kalite güvenceli."),
          O("yalniz", "Ben ve YZ ajanları, dış inceleme yok",
            "Tamamen içeride.",
            "Ev elektriğini kendin döşemek.",
            "Önerilmez; güvenlik-kritik kod incelemesiz kalır."),
      ],
      oneri=["yzuzman"], oneri_neden="YZ ile hız, uzmanla güvence; kimlik ve yürütücü kodu incelemesiz kalmamalı.",
      kaynak=["Uygulanabilirlik incelemesi 9"], etkiler=["K12", "Plan"]),

    S("E03", "ekip", "P1", "sen",
      "Açık kararların sahibi ve son tarihi nasıl belirlensin?",
      "35 açık kararın hiçbirinde karar sahibi veya son tarih yok; ADR'ler \"kapatan\" alanıyla bırakılmış.",
      [
          O("kural", "Ürün kararları sende; teknik kararlar önerilen varsayılan ve teknik inceleyici onayıyla; her karar bir faz sonuna bağlanır",
            "Her açık karara sahip ve faz tarihi yazılır; faz sonuna kadar kapanmayan karar o fazı bloklar.",
            "Proje toplantısında her maddenin karşısına sorumlu ve tarih yazmak.",
            "Açık kararlar tablosuna \"sahip\" ve \"son faz\" sütunları eklenir."),
          O("serbest", "Karar ihtiyaç oldukça verilir",
            "Takvim yok.",
            "\"Sonra bakarız\" listesi.",
            "Kararlar birikir, geliştirme bloklanır."),
      ],
      oneri=["kural"], oneri_neden="Bu karar kitabı bu kuralın ilk uygulaması.",
      kaynak=["Codex D13", "Claude raporu B9"], etkiler=["Açık kararlar", "ADR"]),

    S("E04", "ekip", "P1", "sen",
      "Ana projenin belgeleri nasıl düzenlensin?",
      "Belge yaklaşık 29 bin kelimelik tek bir sayfa. Her inceleme turunda büyüyor ve yeni çelişki bırakıyor; sözlük, değişiklik günlüğü ve okuma yolu yok.",
      [
          O("dort", "Dört parça, tek kaynaktan üretilir",
            "Parçalar: kısa ürün belgesi, sözleşme paketi (şemalar, API ve hata kataloğu), test planı ve karar günlüğü (ADR). Hepsi aynı kaynaktan üretilir; sözlük ve değişiklik günlüğü ortaktır.",
            "Bir binanın mimari, statik ve tesisat projelerinin ve şantiye defterinin ayrı dosyalar olması.",
            "Mevcut belge bölünür; her parçanın okuru ve sahibi belli olur."),
          O("tek", "Tek belge kalır; sözlük, değişiklik günlüğü ve okuma yolu eklenir",
            "Yapı korunur, gezinme kolaylaşır.",
            "Kalın bir kitaba içindekiler ve dizin eklemek.",
            "Daha az iş; ama belge büyümeye devam eder."),
      ],
      oneri=["dort"], oneri_neden="Farklı okurların (sen, geliştirici, test, denetim) aynı belgede boğulmaması için.",
      kaynak=["Claude raporu G1", "Codex (belge nasıl güçlendirilmeli)", "Tutarlılık incelemesi 15"], etkiler=["Belgenin tamamı"]),

    S("E05", "ekip", "P2", "sen",
      "İş takibi hangi araçta yapılsın?",
      "Gereksinimler yalnız HTML içinde duruyor; bir iş takip aracına aktarılamıyor.",
      [
          O("github", "GitHub Issues (repo zaten GitHub'da)", "Her gereksinim ve deney bir iş kaydı olur.", "Kodun durduğu yerde yapılacaklar listesi.", "requirements.json üretilir ve aktarılır."),
          O("linear", "Linear", "Hızlı ve modern iş takibi.", "Ürün ekiplerinin sprint panosu.", "Ayrı araç entegrasyonu gerekir."),
          O("jira", "Jira", "Kurumsal iş takibi.", "Büyük şirketlerin proje yönetimi.", "Kurulum ve lisans maliyeti."),
          O("yok", "Şimdilik yok", "Belge tek kaynak kalır.", "Defterde not tutmak.", "İlerleme görünmez."),
      ],
      oneri=["github"], oneri_neden="Kodun, belgenin ve incelemenin durduğu yerde en az sürtünme.",
      kaynak=["Claude raporu G1"], etkiler=["build.py"]),

    S("E06", "ekip", "P2", "sen",
      "Sürüm ve güvenlik duyuruları nasıl izlensin?",
      "Keycloak, eklentiler ve Frappe düzenli güvenlik yaması yayımlıyor. Kimlik rehberi haftalık izleme öneriyor.",
      [
          O("otomasyon", "Dependabot ve haftalık n8n + OpenClaw raporu; yalnız rapor ve PR üretir",
            "Bağımlılık yamaları için Dependabot; Keycloak ve eklenti duyuruları için haftalık özet. Canlı sisteme kendiliğinden dokunmaz.",
            "Arabanın bakım zamanını hatırlatan uygulama.",
            "n8n iş akışı ve OpenClaw özet adımı kurulur."),
          O("dependabot", "Yalnız Dependabot",
            "Bağımlılık güncellemeleri PR olarak gelir.",
            "Yalnız lastik değişim hatırlatması.",
            "Keycloak eklenti ve lisans değişiklikleri gözden kaçabilir."),
          O("elle", "Elle takip",
            "Duyurular elle okunur.",
            "Bakım zamanını akılda tutmak.",
            "Unutma riski yüksek."),
      ],
      oneri=["otomasyon"], oneri_neden="Tekrarlayan bir izleme işi; otomasyona bağlamak tam yerinde. Canlıya dokunmadığı için güvenli.",
      kaynak=["Kimlik rehberi: otomatik izleme"], etkiler=["K12", "A7"]),

    S("E07", "ekip", "P2", "sen",
      "İlk teslim için hedef zaman ne?",
      "Karar kaydı \"kademeli platform\" seçmiş; önerisi \"henüz süre taahhüdü yok\". Plan zaman içermiyor.",
      [
          O("3", "3 ay", "Kısa ve odaklı.", "Bir mevsimde dükkân açmak.", "Kapsam en küçük dilime iner."),
          O("6", "6 ay", "Dengeli.", "Yarım yılda ürün çıkarmak.", "İlk dilim ve kimlik çekirdeği sığar."),
          O("12", "12 ay", "Geniş.", "Bir yılda platform kurmak.", "YZ yüzeyleri ve portal da sığabilir."),
          O("yok", "Taahhüt yok; dilim kabulüne göre", "Tarih yerine kabul ölçütü.", "\"Hazır olunca açılır\" diyen restoran.", "Plan zamansız kalır."),
      ],
      oneri=None, oneri_neden="Takvim senin iş hedeflerine bağlı; seçimine göre ilk teslim kapsamı daraltılır.",
      kaynak=["Karar kaydı: timeline"], etkiler=["Plan"]),

    S("E08", "ekip", "P2", "sen",
      "Belgede terimler nasıl açıklansın?",
      "AEP, BFF, grant, Run, kanarya, PoC, Desk ve DocType gibi terimler ilk geçtikleri yerde açıklanmıyor; bazı kelimelerin iki anlamı var (\"yüzey\", \"sid\").",
      [
          O("sozluk", "Başa sözlük; her terim ilk geçtiği yerde kısa açıklama; çok anlamlı kelimeler ayrılır",
            "Terimin tanımı hem sözlükte hem ilk kullanımda olur.",
            "Kullanım kılavuzunun başındaki \"Terimler\" sayfası.",
            "Sözlük tek kaynaktan üretilir ve doğrulama betiği tanımsız terimi yakalar."),
          O("yalniz", "Yalnız sözlük",
            "Metin olduğu gibi kalır, sözlük eklenir.",
            "Kitabın sonuna dizin koymak.",
            "Okur her seferinde sözlüğe gitmek zorunda kalır."),
      ],
      oneri=["sozluk"], oneri_neden="Sen ve ekibe yeni katılan herkes için okumayı hızlandırır; senin açıklama kuralınla da uyumlu.",
      kaynak=["Tutarlılık incelemesi 12", "Claude raporu G2"], etkiler=["Belgenin tamamı"]),

    # ------------------------------------------------------------------ KARAR KAYDINDAKİ İDDİALI SEÇİMLER
    S("R01", "kayit", "P2", "sen",
      "Kullanıcı çalışma alanı (workspace) ne kadar kişisel olsun?",
      "Karar kaydı \"tam kişisel workspace\" seçmiş; önerisi \"şablon + kullanıcı özelleştirmesi\". Gerekçe yazılmamış.",
      [
          O("secim", "Tam kişisel (seçimi koru)", "Her kullanıcı kendi panosunu sıfırdan kurar.", "Kişisel not uygulamasında her sayfayı kendin düzenlemek.", "Kurumsal tutarlılık düşer; destek zorlaşır."),
          O("oneri", "Şablon + kullanıcı özelleştirmesi (öneriye dön)", "Şirket şablon verir, kullanıcı üstüne ekler, \"şablona dön\" diyebilir.", "Şirketin hazır pano şablonunu verip kişisel eklemeye izin vermesi.", "Yeni kullanıcı boş sayfa görmez."),
      ],
      oneri=["oneri"], oneri_neden="Yeni kullanıcıya hazır başlangıç, deneyimliye özgürlük verir.",
      kaynak=["Karar kaydı: workspace"], etkiler=["D6"], serbest=True),

    S("R02", "kayit", "P2", "sen",
      "Tarih, seçim ve dosya alanları tarayıcının kendi kontrolünü mü kullansın?",
      "Karar kaydı \"tutarlı özel kontroller\" seçmiş; önerisi \"yerel (native) kontrolü koru, gerektiğinde özel\".",
      [
          O("secim", "Her yerde tutarlı özel kontroller (seçimi koru)", "Her cihazda aynı görünen tarih seçici.", "Tüm cihazlarda aynı görünen özel takvim.", "Klavye, ekran okuyucu ve Türkçe klavye desteği bizim yükümüz olur."),
          O("oneri", "Yerel kontrol, gerektiğinde özel (öneriye dön)", "Telefonda telefonun kendi tarih tekerleği.", "iPhone'da doğum tarihi seçerken çıkan tekerlek.", "Erişilebilirlik ve otomatik doldurma cihazdan gelir; iş azalır."),
      ],
      oneri=["oneri"], oneri_neden="Tarayıcının kendi kontrolleri erişilebilirliği ve mobil deneyimi ücretsiz verir.",
      kaynak=["Karar kaydı: native"], etkiler=["J2", "C5"], serbest=True),

    S("R03", "kayit", "P2", "sen",
      "Desk'teki Client Script davranışları nasıl taşınsın?",
      "Karar kaydı \"tüm davranışları yeniden modelle\" seçmiş; önerisi \"iş kuralını sunucuya taşı\". Bu, yalnız mevcut Desk kullanımı varsa önemli.",
      [
          O("secim", "Tüm davranışlar yeniden modellenir (seçimi koru)", "Her Desk davranışı envanterlenip yeniden tasarlanır.", "Eski evden her eşyayı taşımak.", "En büyük keşif ve regresyon maliyeti."),
          O("oneri", "Yalnız iş kuralları sunucuya taşınır (öneriye dön)", "Görsel davranışlar yeni tasarımla gelir; iş kuralı sunucuda korunur.", "Taşınırken yalnız gerekli eşyayı almak.", "İş azalır; kural kaybı olmaz."),
      ],
      oneri=["oneri"], goster={"soru": "U01", "iceren": ["canli", "pilot"]},
      oneri_neden="Asıl risk iş kuralının kaybolması; görsel davranışlar yeni tasarımla zaten değişecek.",
      kaynak=["Karar kaydı: scripts"], etkiler=["B4"], serbest=True),

    S("R04", "kayit", "P2", "teknik",
      "Uygulama stilleri nasıl yazılsın?",
      "Karar kaydı \"kontrollü CSS-in-JS\" seçmiş; önerisi \"kapsamlı CSS Modules ve katmanlar\". Senin tercih listende SCSS var.",
      [
          O("secim", "Kontrollü CSS-in-JS (seçimi koru)", "Stiller JavaScript içinde, antd ile aynı motor.", "Mobilyanın ve boyasının aynı fabrikadan gelmesi.", "Çalışma zamanı maliyeti ve stil sırası sorunları."),
          O("oneri", "SCSS Modules ve katmanlar (öneriye dön)", "Stiller ayrı dosyada, bileşene kapsamlı.", "Her odanın kendi boya kutusu.", "YZ kod araçları kolay üretir; tercihinle uyumlu."),
      ],
      oneri=["oneri"], oneri_neden="Senin SCSS tercihinle uyumlu; stil sırası sorunları azalır.",
      kaynak=["Karar kaydı: css"], etkiler=["C4"], serbest=True),

    S("R05", "kayit", "P2", "sen",
      "İkon seti ne olsun?",
      "Karar kaydı \"özel domain ikonları\" seçmiş; önerisi \"Ant ikonları + anlamsal takma ad\". Senin arayüz kuralın ise Phosphor'u öncelikli sayıyor.",
      [
          O("phosphor", "Phosphor + anlamsal takma ad (senin kuralın)", "Tüm ikonlar Phosphor'dan; kod ikon adı yerine anlamı kullanır (ör. \"onayla\").", "Tek yazı tipiyle yazılmış bir kitap.", "C8 Phosphor'a göre yazılır; özel ikon yalnız SVG olarak eklenir."),
          O("ant", "Ant ikonları + takma ad (kaydın önerisi)", "antd ile gelen ikonlar.", "Mobilyayla birlikte gelen kulplar.", "Kuralınla çelişir."),
          O("ozel", "Özel çizim ikonlar (kaydın seçimi)", "Her ikon özel çizilir.", "Kendi yazı tipini tasarlamak.", "Çizim, lisans ve bakım maliyeti."),
      ],
      oneri=["phosphor"], oneri_neden="Senin arayüz kuralın zaten bunu söylüyor; belge buna uyumlu hâle gelmeli.",
      kaynak=["Karar kaydı: icons", "Kullanıcı arayüz kuralı"], etkiler=["C8"], serbest=True),

    S("R06", "kayit", "P2", "sen",
      "Erişilebilirlik hedefi ne olsun?",
      "Karar kaydı \"WCAG 2.2 AA\" seçmiş; önerisi \"AA tabanı + seçili AAA\". Belge 44 px dokunma hedefi gibi bazı AAA maddelerini zaten istiyor.",
      [
          O("secim", "WCAG 2.2 AA (seçimi koru)", "Yasal ve sektörel standart düzey.", "Binanın rampa ve asansör standardına uyması.", "44 px hedef ayrı ürün kararı olarak kalır."),
          O("oneri", "AA + seçili AAA (öneriye dön)", "AA temel; 44 px hedef ve güçlü odak görünürlüğü gibi seçili AAA maddeleri.", "Standart rampaya ek olarak dokunsal yol şeridi.", "Belgedeki 44 px kuralı resmî hedefe bağlanır."),
      ],
      oneri=["oneri"], oneri_neden="Belge zaten bazı AAA maddelerini istiyor; hedefi buna göre adlandırmak tutarlılık sağlar.",
      kaynak=["Karar kaydı: a11y-target"], etkiler=["J1"], serbest=True),

    S("R07", "kayit", "P2", "teknik",
      "Canlı bağlantı koparsa yedek olarak periyodik sorgu (polling) olsun mu?",
      "Karar kaydı yalnız Socket.IO seçmiş; önerisi \"realtime + polling yedeği\".",
      [
          O("secim", "Yalnız Socket.IO (seçimi koru)", "Bağlantı koparsa yeniden bağlanana kadar güncelleme gelmez.", "Radyo yayını kesilince haber alamamak.", "Kurumsal ağlarda WebSocket engellenirse canlı güncelleme durur."),
          O("oneri", "Socket.IO + polling yedeği (öneriye dön)", "Bağlantı yoksa birkaç saniyede bir \"değişen var mı\" diye sorulur.", "Radyo kesilince haber sitesine bakmak.", "Olaylar zaten yalnız sinyal olduğu için yedek ucuzdur."),
      ],
      oneri=["oneri"], oneri_neden="Kurumsal ağ engellerine karşı ucuz bir sigorta.",
      kaynak=["Karar kaydı: realtime"], etkiler=["B6", "B10"], serbest=True),

    S("R08", "kayit", "P2", "teknik",
      "Ekran düzeni cihaza göre nasıl uyarlansın?",
      "Karar kaydı \"göreve göre uyarlanan yüzey\" seçmiş; önerisi \"konteyner ve içsel düzen\" (container + intrinsic layout).",
      [
          O("secim", "Göreve göre ayrı yüzeyler (seçimi koru)", "Telefonda ve masaüstünde farklı ekran yapıları.", "Mobil ve masaüstü için ayrı web siteleri.", "İki görünüm arasında durum korunumu ve çift test."),
          O("oneri", "Tek düzen, kutuya göre esneyen parçalar (öneriye dön)", "Aynı ekran sığdığı alana göre yeniden dizilir.", "Esnek mobilyanın odanın boyutuna uyması.", "Daha az kod; yalnız gerçekten gereken ekranlar ayrılır."),
      ],
      oneri=["oneri"], oneri_neden="Tek düzen daha az kod ve daha az test demek; ayrı yüzey yalnız kanıtlanmış ihtiyaçta.",
      kaynak=["Karar kaydı: layout"], etkiler=["J6"], serbest=True),

    S("R09", "kayit", "P2", "teknik",
      "Veri sözleşmesi Frappe'ye ne kadar yakın olsun?",
      "Karar kaydı \"Frappe tiplerine yakın eşleme\" seçmiş; önerisi \"sürümlü bağımsız şema\".",
      [
          O("secim", "Frappe tiplerine yakın (seçimi koru)", "Alan tipleri Frappe'deki adlarıyla gelir.", "Çeviri yapmadan orijinal dilde okumak.", "Daha az eşleme kodu; Frappe'ye bağımlılık görünür kalır."),
          O("oneri", "Bağımsız, sürümlü şema (öneriye dön)", "Frappe tipleri ürünün kendi diline çevrilir.", "Belgeyi kendi dilimize çevirip saklamak.", "Backend değişirse frontend etkilenmez; çeviri katmanı yazılır."),
      ],
      oneri=["secim"], oneri_neden="Backend olarak Frappe'ye bağlısın; yakın eşleme daha az iş ve daha az hata demek.",
      kaynak=["Karar kaydı: contract"], etkiler=["B2"], serbest=True),

    S("R10", "kayit", "P2", "sen",
      "Formlar nasıl kaydedilsin?",
      "Karar kaydı \"alan bazlı otomatik kayıt\" seçmiş; önerisi \"taslak otomatik kayıt + açık gönderim\". Frappe'de gerçek belgeye her kayıt iş kurallarını (hook) çalıştırır.",
      [
          O("secim", "Her alan anında gerçek belgeye kaydedilir (seçimi koru)", "Kullanıcı yazdıkça belge güncellenir.", "Bulut belge düzenleyicilerinin her tuşta kaydetmesi.", "Hook yan etkileri (bildirim, stok hareketi) istemeden tetiklenebilir; ayrı güvenlik envanteri gerekir."),
          O("oneri", "Taslak otomatik kaydedilir, gerçek belge \"Kaydet\" ile (öneriye dön)", "Yazılanlar kaybolmaz ama iş kuralları yalnız açık kayıtla çalışır.", "E-postanın taslakta otomatik saklanması, gönderimin ise düğmeyle olması.", "Yan etkisiz; kullanıcı kontrolü net."),
      ],
      oneri=["oneri"], oneri_neden="Frappe'de kaydın yan etkileri var; taslak ve açık kayıt ayrımı sürprizi önler.",
      kaynak=["Karar kaydı: drafts", "Açık kararlar: autosave"], etkiler=["E2"], serbest=True),

    S("R11", "kayit", "P2", "sen",
      "İlk sürümde hangi yüzeyler olsun: panel, portal, herkese açık site?",
      "Karar kaydı üçünü birden seçmiş; önerisi \"yalnız oturum gerektiren panel\".",
      [
          O("secim", "Üçü birden (seçimi koru)", "Panel, müşteri portalı ve herkese açık site.", "Aynı anda ofis, mağaza ve web sitesi açmak.", "İlk sürüm çok büyür."),
          O("oneri", "Önce panel; portal ve site sonraki fazlarda (öneriye dön)", "İlk teslim yalnız oturum gerektiren panel.", "Önce ofisi açıp işleri oturtmak.", "L8, L9 ve M21 sonraki fazlara kalır."),
      ],
      oneri=["oneri"], oneri_neden="İlk teslimi küçük tutmak kalite ve süre için en etkili karar.",
      kaynak=["Karar kaydı: surface"], etkiler=["L8", "L9", "M21"], serbest=True),

    S("R12", "kayit", "P2", "sen",
      "Desk ile ne kadar eşitlik hedeflensin?",
      "Karar kaydı \"tam işlevsel eşitlik\" seçmiş; önerisi \"aşamalı eşitlik\".",
      [
          O("secim", "Tam eşitlik (seçimi koru)", "Desk'te yapılabilen her şey yeni arayüzde de yapılabilir olmalı.", "Yeni evde eski evdeki her dolabın birebir olması.", "Tam envanter ve en uzun süre."),
          O("oneri", "Aşamalı eşitlik (öneriye dön)", "En çok kullanılan işler önce taşınır.", "Önce mutfak ve yatak odası, sonra depo.", "Kullanım verisine göre sıralama."),
      ],
      oneri=["oneri"], goster={"soru": "U01", "iceren": "canli"},
      oneri_neden="Az kullanılan bir Desk özelliği için tüm geçişi bekletmek verimsiz.",
      kaynak=["Karar kaydı: parity"], etkiler=["B8", "K7"], serbest=True),

    # ------------------------------------------------------------------ TEKNİK VARSAYILANLAR
    S("X01", "teknik", "P2", "teknik",
      "Hata kataloğu ve tek hata biçimi tanımlansın mı?",
      "Adım yükseltme, onay süresi dolması, grant kapsamı aşımı, kota, sürüm uyuşmazlığı ve CSRF hatası için hata türü ve ekran davranışı yazılmamış.",
      [
          O("onay", "Önerilen varsayılanı onayla",
            "Her hatanın kodu, HTTP durumu, Frappe hata türü, tekrar denenebilir mi, ekranda nasıl göründüğü ve telemetri olayı tek tabloda. Özel metotlar için ortak bir JSON hata biçimi.",
            "Arabanın arıza kodu listesi: her ışığın ne anlama geldiği ve ne yapılacağı.",
            "Belgeye hata kataloğu eklenir; E3'teki HTTP koduna dayalı eşleme düzeltilir."),
          O("sonra", "Teknik inceleyiciyle sonra karar",
            "Karar ertelenir.",
            "Arıza listesini sonra yazmak.",
            "Ekipler kendi hata biçimini uydurur."),
      ],
      oneri=["onay"], oneri_neden="Hata davranışı kullanıcı deneyiminin yarısıdır; tek tablo ekipler arası tutarlılık sağlar.",
      kaynak=["Uygulanabilirlik incelemesi 4", "Claude raporu B4"], etkiler=["E3", "M9", "F3", "E7"]),

    S("X02", "teknik", "P2", "teknik",
      "API adları ve sürümleri nasıl olsun?",
      "Capability çağrısı, onay, grant, Run ve oturum uç noktalarının adı, yolu ve sürümü tanımsız; \"bir sürüm penceresi\" ölçüsüz.",
      [
          O("onay", "Önerilen varsayılanı onayla: sürümlü ad alanı, API tablosu, iki sürümlük geçiş penceresi",
            "Her uç nokta sürümlü bir ad alanında (ör. aep.api.v1) yer alır. Tabloda yöntem, yol, yetki, istek ve yanıt şeması, tekrar koruması, hata kodları ve faz bulunur. Eski istemci en az iki sürüm veya 90 gün çalışır.",
            "Priz standardı: yeni cihaz çıksa da eski fiş bir süre takılabilir.",
            "Belgeye API yüzeyi tablosu eklenir."),
          O("sonra", "Teknik inceleyiciyle sonra karar", "Karar ertelenir.", "Prizleri sonra seçmek.", "Paralel geliştirme zorlaşır."),
      ],
      oneri=["onay"], oneri_neden="Frontend ve Frappe ekiplerinin paralel çalışabilmesinin ön şartı.",
      kaynak=["Uygulanabilirlik incelemesi 2"], etkiler=["B1", "H3", "K8"]),

    S("X03", "teknik", "P2", "teknik",
      "Onay ve denetimdeki \"parmak izi\" (hash) nasıl hesaplansın?",
      "Onay kaydı ve revizyon kontrolü içerik ve parametre parmak izine dayanıyor, ama hesaplama kuralı yok. İki taraf farklı hesaplarsa onay hiç eşleşmez.",
      [
          O("onay", "Önerilen varsayılanı onayla: kanonik JSON (RFC 8785) + SHA-256",
            "Veri önce standart biçime getirilir, sonra aynı algoritmayla özetlenir.",
            "İki kişinin aynı listeyi alfabetik sıraya dizip karşılaştırması.",
            "F3, F8 ve I9'daki tüm parmak izleri bu kurala bağlanır."),
          O("sonra", "Teknik inceleyiciyle sonra karar", "Karar ertelenir.", "Listeyi herkesin kendi sırasına dizmesi.", "Onay eşleşmeleri rastgele bozulabilir."),
      ],
      oneri=["onay"], oneri_neden="Standart ve her dilde kütüphanesi hazır.",
      kaynak=["Uygulanabilirlik incelemesi 1"], etkiler=["F3", "F8", "I9"]),

    S("X04", "teknik", "P2", "teknik",
      "Hetzner'da ters vekil (reverse proxy) olarak ne kullanılsın?",
      "Ters vekil ürünü ve yapılandırması tanımlı değil. Ters vekil hostları yönlendirir, TLS'i sonlandırır ve güvenlik başlıklarını ekler.",
      [
          O("nginx", "nginx (Frappe'nin kendi kurulumunun varsayılanı)",
            "Frappe bench üretim kurulumu zaten nginx kullanır.",
            "Evin mevcut elektrik tesisatını kullanmak.",
            "Frappe dokümantasyonu ve topluluk örnekleri doğrudan uyar."),
          O("caddy", "Caddy (otomatik TLS)",
            "Sertifikaları kendiliğinden alır ve yeniler.",
            "Kendi kendini şarj eden cihaz.",
            "Seviye 3 white-label'deki çok sayıda alan adı için kolaylık sağlar."),
          O("traefik", "Traefik (konteyner dostu)",
            "Konteyner etiketlerinden yönlendirme kurar.",
            "Tak-çalıştır priz.",
            "Docker Engine ortamında esnek; Frappe örnekleri daha az."),
      ],
      oneri=["nginx"], oneri_neden="Frappe ekosistemiyle en az sürtünme; seviye 3 white-label gelirse Caddy yeniden değerlendirilir.",
      kaynak=["Uygulanabilirlik incelemesi 14"], etkiler=["M20", "G3"]),

    S("X05", "teknik", "P2", "teknik",
      "İçerik güvenlik politikası (CSP) için tek kullanımlık anahtar (nonce) nasıl verilsin?",
      "G3 betik ve stil için nonce istiyor. Statik Vite sayfasına her yanıtta nonce koyacak bir mekanizma tanımlı değil; antd'nin çalışma anındaki stilleri de nonce gerektirir.",
      [
          O("vekil", "Ters vekil her yanıtta nonce üretir ve HTML'e yerleştirir",
            "Sayfa her istekte yeni bir anahtarla gelir; antd'ye aynı anahtar verilir.",
            "Her ziyaretçiye tek kullanımlık giriş kartı.",
            "G3'e mekanizma yazılır; ters vekil yapılandırmasına eklenir."),
          O("hash", "Derleme anında hash tabanlı politika",
            "Betiklerin özeti derleme sırasında politikaya yazılır.",
            "Misafir listesinin önceden basılması.",
            "Çalışma anında eklenen stiller için yetmez; antd ayarı ayrıca gerekir."),
      ],
      oneri=["vekil"], oneri_neden="antd'nin çalışma anındaki stillerini de kapsayan tek yol.",
      kaynak=["Uygulanabilirlik incelemesi 14"], etkiler=["G3"]),

    S("X06", "teknik", "P2", "teknik",
      "Ortamlar ve dağıtım hattı nasıl olsun?",
      "Belgede geliştirme, test ve canlı ortamları ile CI/CD aşamaları tanımlı değil.",
      [
          O("onay", "Önerilen varsayılanı onayla: yerel (Colima), CI (GitHub Actions), staging ve canlı (Hetzner, Docker Engine)",
            "Her PR CI'da test edilir. Birleşen değişiklik staging'e gider. Canlıya çıkış insan onaylı, tek adımda geri alınabilir.",
            "Mutfakta deneme, tadım masası, sonra servis.",
            "Belgeye \"Dağıtım ve ortamlar\" bölümü eklenir."),
          O("sonra", "Teknik inceleyiciyle sonra karar", "Karar ertelenir.", "Servisi deneme yapmadan açmak.", "Canlıya geçiş süreci belirsiz kalır."),
      ],
      oneri=["onay"], oneri_neden="Senin çalışma ortamına (Mac'te Colima, Hetzner'da Debian) doğrudan uyuyor.",
      kaynak=["Uygulanabilirlik incelemesi 14"], etkiler=["K8", "K10"]),

    S("X07", "teknik", "P2", "teknik",
      "Eski sürüm dosyaları ne kadar saklansın?",
      "Eski istemcinin yeni sunucuyla bir süre çalışması isteniyor, ama eski JavaScript dosyalarının ne kadar tutulacağı yazılmamış. Dosya silinirse açık sekmeler bozulur.",
      [
          O("onay", "Önerilen varsayılanı onayla: en az iki sürüm veya 30 gün; HTML önbelleğe alınmaz, varlık dosyaları uzun süre önbellekte",
            "Açık sekmeler güncelleme sırasında bozulmaz.",
            "Menü değişse de eski menüden sipariş verenin yemeğinin yine gelmesi.",
            "Önbellek politikası dağıtım bölümüne girer."),
          O("sonra", "Teknik inceleyiciyle sonra karar", "Karar ertelenir.", "Menüyü değiştirip eski siparişleri reddetmek.", "Güncelleme anında hata görülebilir."),
      ],
      oneri=["onay"], oneri_neden="Ucuz ve kullanıcıyı güncelleme hatalarından korur.",
      kaynak=["Uygulanabilirlik incelemesi 14"], etkiler=["K8", "H3"]),
]
